### ISSUE TITLE
[BUG/ISSUE] Can't blacklist monitor

### ISSUE THREAD

**Issue by modemjunkie** [marticliment/ElevenClock#1052]
## Before submitting the issue

- [x ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x ] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x ] **I have checked that I am running the latest version of ElevenClock**
-[x ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
When I try to blacklist one of my monitors the dialogue box pops up but when I try to move my cursor over the "yes" button it turns into a  double pointed arrow and won't  click.  Also, while I can tab over to it, hitting enter does not do anything either. 

## To Reproduce
Steps to reproduce the behaviour:
1. Go to ' Monitor tools '
2. Click on "Blacklist this monitor'
3.  Dialog pops up
4. Attempt to select "Yes"
5 See error  - Can't do it.

## Expected behaviour

I expected to be able to blacklist the monitor

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

## Additional context
[elevenclock log.txt](https://github.com/martinet101/ElevenClock/files/10087150/elevenclock.log.txt)

**Comment by martinet101** [comment]
Could you please:
 1. Test the beta version 3.9.7
 2. Send a video of the glitch?

**Comment by martinet101** [comment]
Sorry, forgot to send you the link. This is the beta release: https://github.com/martinet101/ElevenClock/releases/tag/3.9.7-beta1

**Comment by marticliment** [comment]
This issue has been fixed, and the next release will have included the patch
