### ISSUE TITLE
11clock ver. 3.9.6 no longer listens to Clock Features!

### ISSUE THREAD

**Issue by Draskic** [marticliment/ElevenClock#1053]
Hi
Maybe I'm bothering a bit, but 11clock ver. 3.9.6 no longer listens to Clock Features "Change the action done when the clock is clicked, double clicked and middle-clicked" for Change tasks!
I am using Edition Windows 11 Pro
Version 22H2
Installed on ‎12.‎5.‎2022.
OS build 22623.1020
Experience Windows Feature Experience Pack 1000.22638.1000.0
Greeting!
Drasko

**Comment by martinet101** [comment]
Thay are now under the new menu _Clock features_, inetead of under _Clock Settings_:
![image](https://user-images.githubusercontent.com/53119851/204541223-2e7c3975-53cc-46b0-8004-cb0273064f73.png)


I splitted that a few versions ago so it was tidier.

Is that what you were searching for?

**Comment by Draskic** [comment]
Hi 
I noticed that!
But still it is not functional, i.e. it does not work.
I am sending a picture of my settings
Greeting!
![Clock features on my 11clock](https://user-images.githubusercontent.com/24246539/204543614-270e2f87-b142-4ccd-84d3-eefeeef7b25a.jpg)

**Comment by martinet101** [comment]
Could you please share your log?

**Comment by Draskic** [comment]
O.K.
Here is it:
[My 11clock log.txt](https://github.com/martinet101/ElevenClock/files/10113619/My.11clock.log.txt)
Regards!

**Comment by martinet101** [comment]
Yeah, this looks broken. Gotta fix that...

**Comment by Draskic** [comment]
O.K.
Thanks!

**Comment by marticliment** [comment]
This issue has been fixed (sorry for the delay), and the patch will be available with the next version

**Comment by Draskic** [comment]
Alright!
Thank you and Happy New Year!
Drasko

**Comment by marticliment** [comment]
Could you please try this new beta? It should work by now
https://github.com/marticliment/ElevenClock/releases/tag/4.0.0-beta1

**Comment by Draskic** [comment]
Hi
The first command (one click) works. The second (double click) does not work and the third (middle click) works.
On the first one, I put task change, on the second one I disabled it, and on the third one I put Task Manager.
I couldn't put a single command on the double click!
Greetings from Drasko

**Comment by marticliment** [comment]
Could you please attach your log with this new version?

**Comment by Draskic** [comment]
[Log  of 4.0.0 beta 1.txt](https://github.com/marticliment/ElevenClock/files/10355902/Log.of.4.0.0.beta.1.txt)

**Comment by Draskic** [comment]
![Double click test](https://user-images.githubusercontent.com/24246539/210889456-26e7f865-adbf-454c-9da0-3c814b0dc1e9.jpg)

**Comment by Draskic** [comment]
I have set my PC to one click to activate the program!

**Comment by marticliment** [comment]
Your log appears to be correct, no issues are being pushed. 

Could you please set the three actions to different things, re-test and explain which is the current behviour (the clock does nothing when double-clicked, the clock performs an unexpected action, etc.) (and resend me the log)?

**Comment by Draskic** [comment]
O.K.
This is how I set all 3 functions:
1. one click: open run dialog; works flawlessly!
2. double click: Task Manager; does not work in any case and most often opens the run dialog!
3. middle click: opens the start menu; works well!
Regards!
[Log with 3 dif. functions.txt](https://github.com/marticliment/ElevenClock/files/10369003/Log.with.3.dif.functions.txt)

**Comment by marticliment** [comment]
In those cases where it does not open the run dialog, what happens?

**Comment by Draskic** [comment]
1. and 2. as if they were joined!
If I click once, the run dialog opens.
If I click twice, the run dialog opens on the first click, so I don't even get there the second time. The run dialog opens immediately!
The second function (2x click) seems to be too sensitive!

**Comment by marticliment** [comment]
So, it might seem dumb, but as I said, the timeout for the double click is very tight. If you double-click as fast as possible or with an autoclicker, does it still fail?

**Comment by Draskic** [comment]
Definitely!
I don't have that autoclick, but I can't achieve that double click in any case!
At the first click, the 1st function "run" already appears.
I think there should be a delay on the FIRST function so that a double click is possible!
We should go in that direction!
Greeting

**Comment by marticliment** [comment]
From version 4.0.2 and up, you will have an option to increase the period of acceptance of double clicks from 150ms to 300ms, which is likely what is causing your issues.
![image](https://user-images.githubusercontent.com/53119851/225942625-a0dc8c00-b982-46cd-b300-cb3d5e3f204c.png)

**Comment by Draskic** [comment]
O.K.
When will we get 4.0.2 that version?
Greeting!

**Comment by marticliment** [comment]
I don't know exactly, but in the following days

**Comment by Draskic** [comment]
O.K.!
Thanks!

**Comment by Draskic** [comment]
Hi!
Double click works fine on 4.0.3 version!
Congratulations and thank you!
Greeting!
