### ISSUE TITLE
[FEATURE REQUEST] Custom line height suggestions

### ISSUE THREAD

**Issue by albiek1976** [marticliment/ElevenClock#1064]
Hello,

**Is your feature request related to a problem? Please describe.**
I would like to suggest additional custom line height selections. I use fonts that sometimes fall in between what the custom line height is available.  

**Describe the solution you'd like**
The 0.05 increments aren't listed between 0.5-0.8 (0.6, the day of week and date are too tight and 0.7 has the bottom half on the date cut-off) 
I use some fonts that the 0.1 increments are either too tight or too loose. 

<img width="815" alt="EC Screenshot 2022-12-16 131058" src="https://user-images.githubusercontent.com/92185158/208165253-2fa242a3-3233-4e30-9bb8-f026b5c8ba1c.png">
<img width="81" alt="6 size Screenshot 2022-12-16 131310" src="https://user-images.githubusercontent.com/92185158/208165275-d03818e0-edeb-4dd3-9ffc-f1587b1faafe.png">
<img width="82" alt="7 size Screenshot 2022-12-16 133143" src="https://user-images.githubusercontent.com/92185158/208165431-81716068-6649-4d3b-86e3-5666b8b10c43.png">

Thanks

**Comment by marticliment** [comment]
Fixed!
