### ISSUE TITLE
seconds not showing even though the option is enabled 

### ISSUE THREAD

**Issue by Linuxuser1234** [marticliment/ElevenClock#1066]
i have a issue i selected the option show seconds on the clock but nothing happens what am i doing wrong?
![Screenshot 2022-12-22 114019](https://user-images.githubusercontent.com/67390756/209194279-cc994d99-c22b-4db1-9980-07182370de1d.png)

**Comment by HAMSmh** [comment]
same problem

**Comment by HAMSmh** [comment]
I've found out that it doesnt work if there are programs that have an higher window priority.

**Comment by HAMSmh** [comment]
https://user-images.githubusercontent.com/118471985/209225983-7a5ffc67-5ed4-4469-9b87-6ceb323edacd.mp4

**Comment by martinet101** [comment]
Yes, when there's an app in fullscreen, ElevenClock remains hidden, regardless if the app is in foreground or not.
To change this behaviour, you can enable this setting:
![image](https://user-images.githubusercontent.com/53119851/209240114-4c4f8cf4-8a00-4c39-915c-2d505d504e52.png)

**Comment by martinet101** [comment]
Is this what you meant, @Linuxuser1234?
