### ISSUE TITLE
[BUG] Calendar week on 1/1 shows zero

### ISSUE THREAD

**Issue by Jteve-Sobs** [marticliment/ElevenClock#1072]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [X] **I have checked that I am running the latest version of ElevenClock**
- [ ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [X] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
Calendar week on January 1st shows zero in taskbar.

## To Reproduce
Steps to reproduce the behaviour:
1. Show calendar week in taskbar
2. Check calendar week with current week

## Expected behaviour
Shows calendar week 52

## Screenshots
![grafik](https://user-images.githubusercontent.com/46194843/210170997-1c4cee10-9ff4-4f5c-bafc-cf2203d75b24.png)

**Comment by marticliment** [comment]
Hi @Jteve-Sobs,

the 1/1/2023 is the first week of the year, and since it is not monday yet, it is considered to be zero:
![image](https://user-images.githubusercontent.com/53119851/210183876-8e2238a9-e045-4ac1-9fa7-a661283190db.png)
More info: https://strftime.org/.

This is how python works, so it can't be changed.

**Comment by codekumar** [comment]
Plz see attached Image for the Right setting to show the correct week day

![Image](https://github.com/user-attachments/assets/dfbee659-e969-4852-a037-ed15cd21f793)
