### ISSUE TITLE
[BUG/ISSUE] (Enter your description here)

### ISSUE THREAD

**Issue by feistmann** [marticliment/ElevenClock#1073]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by marticliment** [comment]
Hi @feistmann,

what is the issue?

**Comment by feistmann** [comment]
Clock is suddenly reading an hour ahead of time, and all the settings seem correct. I can’t find a way to fix it.Sent from my iPhoneOn Jan 2, 2023, at 3:29 AM, Martí Climent ***@***.***> wrote:﻿
Hi @feistmann,
what is the issue?

**Comment by feistmann** [comment]
It fixed itself today.  Don’t ask me...

**Comment by marticliment** [comment]
Hi feistmann,

this is an issue with the internet time provider. 

Please disable Internet time from the ElevenClock settings:

![image](https://user-images.githubusercontent.com/53119851/210270020-e2b13140-cd58-404e-8f9b-857f34accbc7.png)

![image](https://user-images.githubusercontent.com/53119851/210270013-03cb2fa1-b7ed-4a71-8824-e300df9a9bbe.png)

**Comment by feistmann** [comment]
Perfect.  Thanks.

**Comment by feistmann** [comment]
I did this and it worked until now, BUT I just went in to EC Settings to see if internet time sync was still disabled.  It was, but when I closed Settings clock was fixed

**Comment by marticliment** [comment]
Yes, when using internet time this issue might randomly appear and disappear

**Comment by feistmann** [comment]
I just noticed that when I go in to ElevenO’clock settings it corrects.

**Comment by feistmann** [comment]
Not using internet time and it is still doing that.  What next?

**Comment by marticliment** [comment]
could you please send me your log?

ElevenClock settings - > debugging information - >open log
