### ISSUE TITLE
[FEATURE REQUEST] Language selection in post-installation Wizard

### ISSUE THREAD

**Issue by Kira-Lappo** [marticliment/ElevenClock#1074]
It would be nice to have a lanugage selector on the first screen of the Setup Wizard after the Clock are installed at first time.

**Comment by marticliment** [comment]
![image](https://user-images.githubusercontent.com/53119851/210874917-5a69680d-204b-442e-b961-7a30d2175364.png)
This language picker is loaded before any ElevenClock module is loaded, so it won't support:
 - Theming (dark/light modern UI)
 - Translation (so it is more accessible)

**Comment by marticliment** [comment]
You can find the feature on the new beta
https://github.com/marticliment/ElevenClock/releases/tag/4.0.0-beta1
