### ISSUE TITLE
[BUG/ISSUE] Settings are out of sync with the app state after re-running Wizard

### ISSUE THREAD

**Issue by Kira-Lappo** [marticliment/ElevenClock#1076]
## Describe the bug
Settings are out of sync with the real app state after re-running Wizard.

## To Reproduce
Steps to reproduce the behaviour:
1. Customize clocks, make it display current time with seconds
2. Start Setup Wizard
3. Before any other actions, close Settings page.
   It doesn't affect anything, just for a clarity.
4. Go back to the Wizard window
5. Navigate to clock format page
6. Set any different clock style, in our case select just a date format, without time
7. Complete setup via Wizard and close it
8. Open Settings window and navigate to clock format settings.

## Expected behaviour
Current clock setup corresponds to settings values

## Actual behviour
Settings from Wizard and setting state in Settings page are totally out of sync.

## Screenshots
![image](https://user-images.githubusercontent.com/11411852/210355740-95579cd4-ea10-4d99-84d7-703e1fd81960.png)

## Affected versions
I tested it on 3.9.7-beta

**Comment by marticliment** [comment]
This issue has been fixed, and the fix will come with the next release

**Comment by marticliment** [comment]
You can find the fix on the new beta
https://github.com/marticliment/ElevenClock/releases/tag/4.0.0-beta1
