### ISSUE TITLE
[FEATURE REQUEST] Show day in a year

### ISSUE THREAD

**Issue by Madmatoster** [marticliment/ElevenClock#1082]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
To show day number in a year like we have week number.
It can be by weekday, ie "friday (13)"...
I need it in my job and I usually go here to see it:
https://www.epochconverter.com/daynumbers
Thanks!

**Comment by marticliment** [comment]
Hi,

You need to specify a custom date and time format, and then use the %j element to print the day of the year.
![image](https://user-images.githubusercontent.com/53119851/212470318-0c48462b-404d-4147-af5e-5bfecd85785b.png)

**Comment by marticliment** [comment]
Is this it, right?

**Comment by Madmatoster** [comment]
Yes, this works. I feel ashamed, didn't see custom format in settings.
Thanks!
