### ISSUE TITLE
[BUG/ISSUE] (Enter your description here)

### ISSUE THREAD

**Issue by VenusGirl** [marticliment/ElevenClock#1083]
![11클럭](https://user-images.githubusercontent.com/53147200/212470614-cb766463-e24d-4de8-b0be-379504184f26.png)

When I downloaded it and installed it for the first time, I couldn't see Korean properly and it appeared with a strange code, so I couldn't recognize it.

The installation script encoding does not appear to be accurate.

**Comment by marticliment** [comment]
I suppose your system has the correct codes and this is not the issue. 

I just downloaded the Korean file from jrsoftware.com (that, as listed there, you translated, right? (https://jrsoftware.org/files/istrans/)), and added it as I added other languages. 

Do you have any clue of how could this get fixed?

**Comment by VenusGirl** [comment]
The picture below shows the correct display of Korean.
The Korean file on jrsoftware.com is translated by me.


Maybe Sandboxie (https://github.com/sandboxie-plus/Sandboxie) set the encoding code to UTF-8 BOM.

***@***.***






✧₊⁎˓ VᴇɴᴜsGɪʀʟ-비너스걸💋˒⁎⁺˳✧༚

Now at this moment, my beauty shines the most

Windows용 메일<https://go.microsoft.com/fwlink/?LinkId=550986>에서 발송된 메일입니다.


보낸 사람: Martí ***@***.***>
보낸 날짜: 2023년 1월 15일 일요일 오전 4:59
받는 사람: ***@***.***>
참조: ***@***.***>; ***@***.***>
제목: Re: [marticliment/ElevenClock] [BUG/ISSUE] (Enter your description here) (Issue #1083)


I suppose your system has the correct codes and this is not the issue.

I just downloaded the Korean file from jrsoftware.com (that, as listed there, you translated, right? (https://jrsoftware.org/files/istrans/)), and added it as I added other languages.

Do you have any clue of how could this get fixed?

**Comment by marticliment** [comment]
This issue has been fixed. 

Latest beta already include valid korean translation files for the installer

**Comment by VenusGirl** [comment]
It is still not displayed in Korean in the installer.

**Comment by marticliment** [comment]
Are you uing this beta release?
https://github.com/marticliment/ElevenClock/releases/tag/4.0.1-beta1

**Comment by VenusGirl** [comment]
The one I installed is 4.0.1-beta1.

If you look at the picture below in the list, you can't see Korean.

I think the Korean script is missing.

![설치 002](https://user-images.githubusercontent.com/53147200/213426549-8f1035be-b4c5-4384-ab33-b1ef81d3c8ba.png)

![설치 004](https://user-images.githubusercontent.com/53147200/213426579-ad8cec97-f783-4fab-94fd-42af9e5409b8.png)

**Comment by marticliment** [comment]
And then which language is the one shown in the same picture?

**Comment by VenusGirl** [comment]
The first picture shows Korean accurately on the installation screen of Sandboxie-Plus.

The second picture is the installation screen of ElevenClock, but I chose it randomly because I couldn't see Korean.

Because both programs use the same installer, the installation process is the same.

**Comment by marticliment** [comment]
![image](https://user-images.githubusercontent.com/53119851/213469597-bb73d84a-0108-41a8-b520-338a651bb8d5.png)
It is now properly encoded. For whatever the reason it did not load the fixed lang file

**Comment by VenusGirl** [comment]
Korean is correct in the picture.
