### ISSUE TITLE
[FEATURE REQUEST] Click to show clock.

### ISSUE THREAD

**Issue by 23SRLITheGamer** [marticliment/ElevenClock#1086]
**Is your feature request related to a problem? Please describe.**
I don't need always to have the clock open with seconds on. 
I would prefer to be able to just temporarily see it for I would say a minute or two then have my regular clock back.

**Describe the solution you'd like**
Clicking where it is supposed to be will show it for two minutes, then hide it again.
Basically an inverse of the click to hide that it has right now.

**Comment by marticliment** [comment]
Due to the technical diffculty and the need of a complete rewrite of the base code, this feature will not be worked on
