### ISSUE TITLE
【BUG】软件无法打开

### ISSUE THREAD

**Issue by SaintChangeTheWorld** [marticliment/ElevenClock#1088]
系统：
版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎9/‎29
操作系统版本	22621.1105
体验	Windows Feature Experience Pack 1000.22638.1000.0

BUG描述：
我下载了最新的4.0.0版本，安装完成后运行没有该进程，任务栏中也无法找到该软件。再次尝试问题依旧。

补充说明：
在以前的版本中也遇到过此情况。开始的时候软件运行是正常的。但是在用了一段时间（不足一个月）后软件就无法正常运行了。

期望得到的解答：
1.改款软件需要安装哪些环境才能正常运行么？若是，则请告知环境名称及其下载链接。
2.是否你也遇到过此类情况，怎么解决的？

**Comment by SaintChangeTheWorld** [comment]
i need help

**Comment by SaintChangeTheWorld** [comment]
怀疑应该是我改了微软雅黑的字体包造成的

**Comment by marticliment** [comment]
Do you have any third party antivirus that could have blocked ElevenClock?
