### ISSUE TITLE
[FEATURE REQUEST] Maintain the Microsoft Weather shown along with the clock on the left.

### ISSUE THREAD

**Issue by albiek1976** [marticliment/ElevenClock#1091]
**Hello, .**
I would like to have the ability to see and use the widget on the left side of the taskbar. (The weather temperature and icon)
and still, have the clock

**Here's my solution to remedy the issue**
 
In ElevenClock settings 
Clock Position & Size

A separate independent of the right user-operated control needs to be added with a 
slider and a checkbox that will control the position of the left clock.

The name and control that would fix this could be called

Left-side clock horizontal position adjustment.

So the weather can be shown and also have a clock offset on the left side. 

Attached will be where I'd like the control to be able to position the clock. a rectangle will show the area. 

Thanks!

<img width="1915" alt="2nd clock" src="https://user-images.githubusercontent.com/92185158/213053995-f8aef6f5-5999-4126-8acf-98caa31219a8.png">

**Comment by marticliment** [comment]
to do this, you can just set anl x offset to your left side clock, doing the folloging:

right click the clock - > monitor tools - > settings for this clock

enable customizing only that clock and clone the style from the global settings

under clock position, enable x offset and drag the slider so tí shows on the desired position.

**Comment by marticliment** [comment]
did it help?

**Comment by albiek1976** [comment]
Hello,
Sorry for the delayed response.
No, It didn't help. It actually made other issues.
I had to reset the app to fix your fix.

The steps you had me follow had the clock on the left completely disappear from the monitor I trying to do your fix. It made the clock on the right pulsate at a fast speed and made it unreadable.

**Comment by albiek1976** [comment]
I redid the instructions again, and there was a step I missed.
I was able to move the left side on all monitors. 

Thanks for all your help!
