### ISSUE TITLE
[BUG/ISSUE] (design issue, maybe because of screen resolution)

### ISSUE THREAD

**Issue by krrdudub** [marticliment/ElevenClock#1095]
its nothing that big, just an design issue. The clock overlaps about 3-4 pixels of the sound/speaker icon from windows.
my system is windows 11, i got no special settings set and the resolution of my monitor is 2560x1440.
i tried it to fix by changing width etc, but theres no way to get rid of this design issue.
Sincerely
Jan

![image](https://user-images.githubusercontent.com/47592280/213724639-782e1f61-9067-409a-a87a-f49da6349006.png)

**Comment by marticliment** [comment]
Hi Jan,

This issue is listed in the known issues section. You can fix this by either setting a smaller font size or by specifying a x offset for your clock. 

Did this help?

**Comment by krrdudub** [comment]
selecting a smaller font size doesnt help, and i dont know how to specify a x offset for this application

**Comment by marticliment** [comment]
![image](https://user-images.githubusercontent.com/53119851/213731083-dccbb5d4-cab3-484b-b38e-4485246be2bd.png)
