### ISSUE TITLE
[BUG/ISSUE] (Eleven Clock disappears when windows start menu is opened)

### ISSUE THREAD

**Issue by thopri** [marticliment/ElevenClock#1103]
## Before submitting the issue

- [X ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ X] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [ X] **I have checked that I am running the latest version of ElevenClock**
- [ X] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [X ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
Eleven Clock disappers when windows menu is opened, it comes back when menu is closed
## To Reproduce
Steps to reproduce the behaviour:
1. Open Windows menu

## Expected behaviour
Clock to not disapper

## The Log
No log output 

## Additional context
Have tried enabling and disabling different options that I had set from default and there was no change in behviour.

**Comment by marticliment** [comment]
This issue is listed in the known issues section:

> **The clock flashes when clicking the taskbar or hides when opening the start menu**
This happend because of Microsoft's z-index policy, where a focused window (in this case the taskbar) cannot be overlapped by an unfocused window (the clock). The clock will show again when the taskbar loses focus.
