### ISSUE TITLE
[FEATURE REQUEST] Add support for Buddhist Era (BE)

### ISSUE THREAD

**Issue by ikkue** [marticliment/ElevenClock#1108]
**Is your feature request related to a problem? Please describe.**
Currently, the clock doesn't show the year in Buddhist Era even if the Regional settings are set to display it.

![ภาพ](https://user-images.githubusercontent.com/11213135/216927648-fcea42db-fe4c-485b-b70f-67de827eb7f6.png)
![ภาพ](https://user-images.githubusercontent.com/11213135/216927936-8ddf88f6-5938-408a-b0a0-69b807ac573a.png)

As you can see from the two pictures above, the year is set to show as 2566, but ElevenClock still shows it as 2023.

**Describe the solution you'd like**
I want the year format to change according to the regional settings, not just for Buddhist Era, but for other year formats as well.

**Comment by marticliment** [comment]
Hi @ikkue, could you please post your log here?
ElevenClock settings -> Debbigging information -> Show log

**Comment by ikkue** [comment]
[ElevenClock Log 2023-02-06.txt](https://github.com/marticliment/ElevenClock/files/10662599/ElevenClock.Log.2023-02-06.txt)

**Comment by marticliment** [comment]
I see that you are using an incorrect internet time URL.

Could you please remove it and test again?

**Comment by ikkue** [comment]
Are you saying that the Google Public NTP is causing this problem?

**Comment by marticliment** [comment]
It might, since you are providing a NTP url in place of an api one, what is causing ElevenClock to raise errors and exceptions. 

The locales are handled by Python, and it might be the failsafe mode (raised by the incorrect time protocol given) what is generating a _starndard_ time formart

**Comment by ikkue** [comment]
I have removed the NTP from the ElevenClock settings, but I still don't know what to do with this setting in Control Panel
![image](https://user-images.githubusercontent.com/11213135/219411463-ccc9ecd1-ac4b-4e88-a4df-b13676dc6fae.png)
Should I turn it back on? Should I switch back to using Microsoft's?

**Comment by marticliment** [comment]
This settings in the control panel won't affect ElevenClock at all, you can use google's one (here it will actually work) or revert to microsoft's one.

Now, if the issue persists, i will need you to send me back your log again

**Comment by ikkue** [comment]
I have turned "Set a custom network time provider" off, restarted ElevenClock, and reloaded the clocks several times, but the year still appears as 2023 rather than 2566.
![image](https://user-images.githubusercontent.com/11213135/219435179-46fc95f2-4465-49d5-bd46-75d23b16abd9.png)
This is also the case with hovering over it.
![image](https://user-images.githubusercontent.com/11213135/219435277-1318bdde-684a-473f-8fe5-80254730e09c.png)
Here's the log:
[ElevenClock Log 2023-02-17.txt](https://github.com/marticliment/ElevenClock/files/10758512/ElevenClock.Log.2023-02-17.txt)

**Comment by marticliment** [comment]
Hi @ikkue,

I have been researching this, and I'm afraid the library ElevenClock uses to get the current system time does not support Budhist era. 
Consequently, since I can't modify the library so buddhist era works, I can't really fix that.

However, since the only thing wrokg is the year, a possible solution could be specifying a custom date and time format on ElevenClock, and instead of using thew %Y element for the year, you could manually write 2566 (you'd need to change this every year.)

I'm sorry :(

**Comment by ikkue** [comment]
That's understandable. I will try and do that!
