### ISSUE TITLE
[FEATURE REQUEST] Option to make it clicktrough

### ISSUE THREAD

**Issue by limacohen** [marticliment/ElevenClock#1109]
**Is your feature request related to a problem? Please describe.**
W11's "Action Center" has this massive "Notifications" area that can't be hidden, even though I have no notifications. I usually just disable it, however this has the side effect of disabling the "calendar" feature in ElevenClock. I also use StartAllBack that has it's own calendar flyout in W10 style, but it's only accessible if you click their clock replacement, which sits below EC.

**Describe the solution you'd like**
So, instead of asking for a proper calendar flyout in EC, I figured it would _maybe_ be easier to add a "Clicktrough" action to the list.

**Comment by marticliment** [comment]
That can't be possible, at much it could disable the click action.

However, there's an option to hide the clock during 10 seconds when clicked, which woulkd allow you to click on your calendar:
![image](https://user-images.githubusercontent.com/53119851/217340169-de3661d8-86c4-4d11-a823-a8449478765d.png)

**Comment by limacohen** [comment]
Yeah, I was using that as a workaround :D
I guess I'll keep using it. Thanks anyway!

PS: Btw if anyone knows how to remove the "Notifications" section from the Action Center, please do share.
