### ISSUE TITLE
[FEATURE REQUEST] Battery Percentage for laptop

### ISSUE THREAD

**Issue by Raj9039852537** [marticliment/ElevenClock#1119]
**Is your feature request related to a problem? Please describe.**
I would like to suggest addition of battery percentage to elevenclock since microsoft team is very much lazy to add simple yet useful features themselves. 
It is very much useful for laptop users. since only battery icon is shown without actual percentage.

**Comment by marticliment** [comment]
This was discussed before, but it was decided that it came out-of-scope for this application.

There are lots of other tools that can do that

**Comment by Raj9039852537** [comment]
Thanks 👍
Now I can uninstall it and use others 😁
