### ISSUE TITLE
[FEATURE REQUEST] Forced Font Weights?

### ISSUE THREAD

**Issue by TheWolfBunny64** [marticliment/ElevenClock#1126]
When I tried to use the Super Mario Bros. NES font (A font I created via FontStruct) for ElevenClock, the font was in bold.

It's not supposed to be like that! Do you think you can add in a forced font weight feature in the settings?
Like, a feature where you can pick a font weight between 100 and 900? 400 is like the normal weight.
This could be very helpful for fonts that don't have bold and italic styles by default.
Please take this into consideration, Marti.

**Comment by marticliment** [comment]
You should be able to do that through the font dialog picker. 

Please note that some fonts do not support bold/italic, and in the same way they might not support non-bold sytles. Especially if you bbult that font, you might find that it can not show itself as a lighter one.

Anyways, could you please share that font with me so I can test it locally?

**Comment by TheWolfBunny64** [comment]
Yes. Here you go. Once you use this font with ElevenClock, then you'll know what I'm talking about.
https://drive.google.com/file/d/10bCAxc4-PxVnD5lqDZFi7POS8YNhQpI1/view?usp=drive_open

**Comment by marticliment** [comment]
That's what I was saying. Your font doesn't have a _light_/_thin_ variant. There's only the regular, and as a consequence, Qt can't render it bolder or lighter. 
![image](https://user-images.githubusercontent.com/53119851/220720639-5904ab25-6556-4105-8d68-a6301f309605.png)
You would need to build a light font and bundle it with the regular one, juat as segoe Ui does:
![image](https://user-images.githubusercontent.com/53119851/220720944-e9681882-3800-455a-a0e7-c2ba8635533f.png)
