### ISSUE TITLE
[BUG/ISSUE] I think there is a Chinese translation error

### ISSUE THREAD

**Issue by liyuhaolol** [marticliment/ElevenClock#1127]
![222](https://user-images.githubusercontent.com/16422963/221366814-47465962-8527-4d8f-b851-a7589d8a4aa8.png)
- The Chinese translation of this option means: Add a "Show Desktop" button to the left of each clock。
![3333](https://user-images.githubusercontent.com/16422963/221366954-810e47a6-7973-4527-b55d-b1003ab0aa8c.png)
- But as shown in the picture, shouldn't the "Show Desktop" button be on the right side of each clock? ? ?
- So is the translation supposed to be "右侧" instead of "左侧"？？？

**Comment by marticliment** [comment]
I have updated the strings. 

The change should take 2 or 3 days to apply
