### ISSUE TITLE
Why does 11Clock not turn on intermittently?!

### ISSUE THREAD

**Issue by Draskic** [marticliment/ElevenClock#1132]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by Draskic** [comment]
After the last update of the Insider program (beta chanell), I often have the phenomenon that 11Clock does not turn on! Today, for example, when only "Power Toys" was updated, it did not turn on!
No reset or reinstallation of the latest version (4.0.1) helps! It just won't turn on! Even 11Clock settings don't work!
In Windows 11 Startup there is!
My data: Edition Windows 11 Pro
Version 22H2
Installed on ‎12.‎5.‎2022.
OS build 22623.1325
Experience Windows Feature Experience Pack 1000.22639.1000.0
I think this should be considered!

**Comment by Draskic** [comment]
My hidden icons are: 
![My hidden apps](https://user-images.githubusercontent.com/24246539/222392462-6b6d72d6-299d-4375-8d6c-0693e6354699.jpg)

**Comment by marticliment** [comment]
When running ElevenClock manually, does it then run?

**Comment by Draskic** [comment]
No. And also and Settings! The settings only "blinks" one moment.

**Comment by marticliment** [comment]
Which windows version are you running?

Can you confirm that your antivirus is not blocking ElevenClock?

**Comment by marticliment** [comment]
> I tried to make exceptions on both Malwarebytes and Kaspersky, but after the reset it's the same thing! 🤔

It is present on %userprofile%/appdata/local/programs/elevenclock

**Comment by Draskic** [comment]
Hi
Yes I found it!
The funniest thing is that this afternoon I turned on the PC and 11Clock appeared!
I don't know why because I might have tried it with a reset before and now I've turned it on!
In Malwarebyte it is in the "Allow list": C:\Users\Tata\AppData\Local\Programs\ElevenClock\ElevenClock.exe, and in Kaspersky there are two: Malwarebytes and 11Clock (Trusted and Manage excl. ).
It works for now!
Greeting!

**Comment by marticliment** [comment]
If it disappears again, let me know!

**Comment by Draskic** [comment]
👍O.K.

**Comment by Draskic** [comment]
It still works!
And I still expect that!
Greeting!

**Comment by marticliment** [comment]
then let me close this issue, and if the issue persists, reporlst here and I will reopen this.

**Comment by Draskic** [comment]
O.K. You can close it!
Thanks!
