### ISSUE TITLE
[BUG/ISSUE] (the clock in the second screen remains once the application is uninstalled )

### ISSUE THREAD

**Issue by GoDzNiCk** [marticliment/ElevenClock#1134]
this is the problem 
how can i resolve it?
please help me
![image](https://user-images.githubusercontent.com/126949953/222887510-12be3e28-8694-4d5c-989b-0a854a7c45aa.png)

**Comment by marticliment** [comment]
Windows has its own clock in the second screen now, they added it in February last year
.
