### ISSUE TITLE
[BU11Clock turns off during start program activation in Windows 11!!

### ISSUE THREAD

**Issue by Draskic** [marticliment/ElevenClock#1137]
## Before submitting the issue

- [ ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [ ] **I have checked that I am running the latest version of ElevenClock**
- [ ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>
It simply shuts down!
11Clock turns off during start program activation in Windows 11!!

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock 
[Log of problem.txt](https://github.com/marticliment/ElevenClock/files/10945195/Log.of.problem.txt)
Log.

**Comment by marticliment** [comment]
Is it happening again?

**Comment by Draskic** [comment]
Hi
It doesn't repeat again that it disappears when turning on the PC, but I noticed another inconvenience: if the "Start" button from Windows is activated, the 11Clock disappears and it is necessary to click again in "Desktop" to appear! I tried one item at a time in Settings, but nothing helps! It just disappears!
Greeting!

**Comment by marticliment** [comment]
This is listed on the known issues, and it is caused by thew way in how Window Manager works. 
Focused top-level windows (such as the start menu) cannot be covered by other top-level windows such as ElevenClock.

**Comment by Draskic** [comment]
Alright!
I understand!
Greeting!
