### ISSUE TITLE
The middle click with the mouse initiates the setup itself, and not the set function.

### ISSUE THREAD

**Issue by Draskic** [marticliment/ElevenClock#1142]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
Hi
One observation: often the middle click with the mouse initiates the setup itself, and not the set function (in my case Task manager).
Otherwise, double clicking the mouse works very well (in Fixes).
This is for the 4.0.4 version!
Greeting!

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
[Log of the observation.txt](https://github.com/marticliment/ElevenClock/files/11016034/Log.of.the.observation.txt)


If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by marticliment** [comment]
Can you please send a video of this?
There's no logical way I can think of in that the app has the ability to do that.

**Comment by Draskic** [comment]
Hi
I can't give you a video of those actions because I don't have any recorder for it!
I tell you that I have the calendar as the first function (one click), the second (double click) for Task actions, and the middle click is the Task manager, which almost never works, but the first action or the second is called!
Greeting!

**Comment by marticliment** [comment]
The setup being launched is a thing that happens repeatedly?

**Comment by Draskic** [comment]
Yes, very often. Hard to get with middle click Task manager! "Setup" by 11Clock appears very often! The ratio of such events is 1:3 to 4.
But just a moment! When I examine it now, I see that it is necessary to hold the middle click LONGER, and not just squeal!
Yes, exactly! You need to hold the middle click (Wheel) LONGER!
And when you just click briefly, you get Setup as well as right click (standard from 11Clock)
I don't understand what the matter is because the mouse is from Logitech (M705), new!
But that's it!
Greeting!

**Comment by marticliment** [comment]
This also happens to me.

For whatever the reason, short middle clicks are identified as regular clicks. I have created a playground and it always behaves like this for me.
