### ISSUE TITLE
12hr clock

### ISSUE THREAD

**Issue by Nizzergh** [marticliment/ElevenClock#1153]
**Is your feature request related to a problem? Please describe.**
Cant find option to only show a 12hr clock
**Describe the solution you'd like**
Option to only show a 12hr clock

**Comment by marticliment** [comment]
You can do two things:
a) change your regional settings on Windows settings so the time shows in 12h format (you will need to restart ElevenClock)
b) Set a custom time format and build your own format using your custom format strings:
![image](https://user-images.githubusercontent.com/53119851/227991890-8e8fa3ac-54d0-4010-a130-882b1ffa7452.png)

**Comment by marticliment** [comment]
Please reply here for further doubts

**Comment by Nizzergh** [comment]
Hi Martin

Sorry for the delay as I didnt realise you email however thank you for the response. I'll try what you mentioned and get back to you if required. BTW this is a really good app.

Regards
________________________________

**Comment by Nizzergh** [comment]
Hi Martin

I've changed my Windows setting to 12hr however it hasnt changed ElevenClock. Can you please let me know what to type in the ElevenClock box for custom date and time, as I read it but aren't familiar with Python strftime
[cid:99b6b5b3-02f9-4a8e-9aba-f79bc6cc55ca]

For the time I would like:
7:30 AM or just 7:30

Regards
________________________________

**Comment by marticliment** [comment]
After changign Windows settings, make sure to quit and relaunch ElevenClock.

**Comment by Nizzergh** [comment]
Sorry please ignore
For the time I would like:
7:30 AM or just 7:30

It should be :
For the time, when its PM I would like:
7:30:29

________________________________

**Comment by marticliment** [comment]
ElevenClock does not support changing the date and time format dynamically. 

The examples you shown can be achieved with the following:
7:30 AM: `%-I:%-M %p`
7:30: `%-I:%-M`
7:30:29: `%-I:%-M:%-S`
.

If you only want the time, this woud be it. But if you want the date, you'd need something like this:

```
%-I:%-M %p
%-d/%-m/%Y
```

**Comment by Nizzergh** [comment]
Hi Marti

Thank you for that and I tried you're suggestions, they work however I had to delete the - symbols.
Also now the PM time looks like this:
07:30:00

Do you know how to remove the first zero so it looks like this:
7:30:00

regards
________________________________

**Comment by Nizzergh** [comment]
The reason is I need the clock large however its hovering over my taskbar icons and reducing a digit will be beneficial.

________________________________

**Comment by marticliment** [comment]
Sorry, replace the `-` you removed for `#`. You will then remove the padded zeros

**Comment by marticliment** [comment]
Hello,

Please try Enable "Disable hiding the default windows clock"
![image](https://github.com/marticliment/ElevenClock/assets/53119851/9fccfcc2-a53f-411b-94a0-49572e270465)

**Comment by Nizzergh** [comment]
Hello Marti

I tried to different versions of enabled/disable, what happens is the shadow blinks a bright colour then goes back to the shadow but still doesn't go away. My windows version is higher than 22631.

Regards
________________________________

**Comment by Nizzergh** [comment]
Sure I'll try to do it this weekend, thanks Marti
________________________________

**Comment by Nizzergh** [comment]
Hi Marti

Do you have a private email address I can send it to, as github refused the mail as it was too large.

Thanks
________________________________

**Comment by marticliment** [comment]
You can find my email on my profile

**Comment by Nizzergh** [comment]
Hi Marti

I've sent you the video to that email, regards.
________________________________

**Comment by Nizzergh** [comment]
Hi Marti

I tried that last time and it didnt go however I've tried it again it has disappeared, typical 🙂

Thanks for your advice, great app
________________________________

**Comment by Nizzergh** [comment]
Hi Marti

I hope you dont mind me asking another thing. I use a large monitor and have maxed out the width of the click. Can you please extend only the coloured width background by ~ 25% so I can use larger numbers, regards.


________________________________

**Comment by Nizzergh** [comment]
sorry typo:

have maxed out the width of the clock
________________________________

**Comment by marticliment** [comment]
> Hi Marti I hope you dont mind me asking another thing. I use a large monitor and have maxed out the width of the click. Can you please extend only the coloured width background by ~ 25% so I can use larger numbers, regards.

There has been another request for this, and I will do on the next release.
However, if you want to change it right now, you can edit the `ClockFixedWidth` file located under %userprofile%\.elevenclock

**Comment by Nizzergh** [comment]
Thanks Marti and hope you have a Merry Christmas and Happy New Year
________________________________
