### ISSUE TITLE
[BUG/ISSUE] The option to only display clocks on secondary monitors seems to be broken or removed?

### ISSUE THREAD

**Issue by alkatar21** [marticliment/ElevenClock#1160]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [ ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
Since one of the last versions, the clock is no longer automatically hidden on the main screen, showing it only on additional screens. I was sure that there was an option for this, but I can't find it anymore.
I have now blacklisted the monitor as a workaround.
The main screen is often another external screen, so backlisting each monitor if it is the main monitor and adding it again if it is another one is not really beneficial.

## To Reproduce
Steps to reproduce the behaviour:
1. I think one of the v4 Updates caused it to happen.

## Expected behaviour
That I can disable the clock for the main screen, as it was previously the case.

**Comment by marticliment** [comment]
You can blacklist monitors by right-clicking a clock -> clock tools -> Blacklist screen
