### ISSUE TITLE
Formatting possible ?

### ISSUE THREAD

**Issue by 171252** [marticliment/ElevenClock#1163]
Hello,
![grafik](https://user-images.githubusercontent.com/97844259/229082860-6ce4a37c-5abd-4df9-9c48-bb3b863b1e98.png)
![grafik](https://user-images.githubusercontent.com/97844259/229082922-9ea151c4-565f-4449-939f-cfb9f6cee328.png)
![grafik](https://user-images.githubusercontent.com/97844259/229082983-2710d02f-bafa-430e-aecd-84980a8d7abc.png)

This is what my display looks like. Is it possible to set it up so that it looks a bit more formatted? For example, that in Friday (the last picture) the "11" is exactly above the "31"... 
Weekday and KW are left-aligned, that's fine, but what follows is a bit unsorted - I think.

Otherwise ElevenClock is wonderful!!!

Thank you very much for your attention!

Friendly greeting

**Comment by marticliment** [comment]
You could maybe align the clock text to the center, or replace the %A for %a in your custom format (you are using one, right?) so it looks more consistent

**Comment by 171252** [comment]
Thanks for the quick feedback. I have now solved it differently and packed the time forward.
![grafik](https://user-images.githubusercontent.com/97844259/229127980-5cc194bf-9a9b-4cf5-93cd-7912f63c629a.png)
![grafik](https://user-images.githubusercontent.com/97844259/229128015-74825a26-6c9c-44f0-9014-b73b98a37425.png)
Am then so satisfied - best thanks!
