### ISSUE TITLE
[ISSUE] Can't open ElevenClock

### ISSUE THREAD

**Issue by panther7** [marticliment/ElevenClock#1170]
Can't open ElevenClock if "all" available monitors on blacklist (UI is not visible) and tray icon is hidden.

Expected solutions:
- Remove "hide" option for tray icon
- Show tray icon, if UI is hidden

~~Actually is not posible open app and change settings.~~

@marticliment

**Comment by marticliment** [comment]
you can open ElevenClock settings directly, can't you?

**Comment by panther7** [comment]
Yes, it can posible, but it is not intutive (i think).

**Comment by marticliment** [comment]
What I might do also is to allow ElevenClock to be reset from the installer, so users can reset ElevenClock if they really mess up.
