### ISSUE TITLE
ElevenClock overlaying network/sound icon in systray when using custom format (date and time in one line)

### ISSUE THREAD

**Issue by mavvynet** [marticliment/ElevenClock#1179]
This is what the current Windows 11 systray looks like without ElevenClock:
![screenshot 1682285672](https://user-images.githubusercontent.com/11293378/234161206-7a645c8c-d55a-4efc-afdc-774e3e84e192.jpg)

When I use a custom date and time format like "[ %a, %b %d | %H:%m ]" it will overlay above mentioned network/sound icons:
![screenshot 1682285673](https://user-images.githubusercontent.com/11293378/234161414-b8521806-14fa-4f46-9a79-3e2ad2a540c4.jpg)

The network/sound icons are rather some kind of controlpanel for some quick settings:
![screenshot 1682285674](https://user-images.githubusercontent.com/11293378/234161541-259c67b7-c940-4a39-9191-51217b0e2d5a.jpg)

If possible at all, maybe ElevenClock could offer an option to increase the canvas area of the clock.

**Comment by marticliment** [comment]
Hello,

Please see the known issues: https://github.com/marticliment/ElevenClock/wiki#known-issues
