### ISSUE TITLE
[BUG/ISSUE] The latest installer install v4.1.1 as v4.1.0

### ISSUE THREAD

**Issue by horihiro** [marticliment/ElevenClock#1182]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
As the following screenshot, the release v4.1.1 is registered as `v4.1.0` in Windows though the installer for v4.1.1 is used. 
![image](https://user-images.githubusercontent.com/4566555/235337559-89097d08-3617-459a-82a2-a4946f74bfb6.png)

## To Reproduce
Steps to reproduce the behaviour:
1. Open Command Prompt.
2. Execute `winget install --id SomePythonThings.ElevenClock`
3. List installed apps in Settings.

## Expected behaviour
It is expected that this would be shown as `v4.1.1`

## Screenshots
\# attached as above

## Additional context
Due to the version mismatch, winget misunderstands that v4.1.0 is installed and there is an available update.
![image](https://user-images.githubusercontent.com/4566555/235338209-b668c122-d35a-4205-ac76-161df456a0b3.png)

**Comment by zotabee** [comment]
I confirm the issue on my side. winget sourced installer installs it as "4.1.0".

Installed the store version originally and WingetUI will try at each statup to update it.

**Comment by marticliment** [comment]
This issue has been fixed, and changes will be refleted once ElevenClock 4.1.1.1 gets published on winget.
You can install it manually to get the effects instantly
