### ISSUE TITLE
When connected over VPN, the time is showing the remote endpoint time

### ISSUE THREAD

**Issue by fredriklundholm** [marticliment/ElevenClock#1183]
I clock application is useful for showing the time of the machine where it physicalle resides.

If I connect over VPN to other machine using Softether VPN the time displayed no longer represents the time where I reside, but the time of the remote computer. This is an unwnted feature. Windows clock is not tricked by VPN. Elevenclock should not be tricked.

**Comment by marticliment** [comment]
You can do two things to fix that:
1. Disable internet time (ElevenClock settings -> Network time)
2. Specify a custom time server (ElevenClock settings -> Network time -> Custom time provider URL)
