### ISSUE TITLE
[BUG/ISSUE] ElevenClock doesn't adjusts on resolution / screen changes

### ISSUE THREAD

**Issue by xAstroBoy** [marticliment/ElevenClock#1186]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
ElevenClock doesn't adjust itself on resolution changes.

## To Reproduce
Steps to reproduce the behaviour:
On Every resolution change, eleven clock will stay stuck somewhere in the screen.

## Expected behaviour
Reset itself and re-adjust itself on any resolution / screen changes.

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by marticliment** [comment]
This issue will be fixed on the next release
