### ISSUE TITLE
[FEATURE REQUEST] Brief description

### ISSUE THREAD

**Issue by CComparon** [marticliment/ElevenClock#1191]
## Is your feature request related to a problem? Please describe.

I love many features provided by ElevenClock, but as a Windows power user looking for specific improvements on the default taskbar clock, the showstoppers for me are:
1. I have multiple monitors with taskbars of different heights. I can't afford to have a clocks that eat screen real estate here and there.
1. My main pain point with the default Windows clock is the lack of ability to display time in multiple timezones side by side.

## Describe the solution you'd like

Referring to the 2 points above:
1. I would love a replacement that actually replaces the default Windows clock in the task bar rather than bring its own floating windows.
1. I would love being able to see something as simple as this:

![image](https://github.com/marticliment/ElevenClock/assets/12992190/113dec62-9fb5-4f4a-a40e-0784f840dfb7)

Many thanks and keep up the great work on ElevenClock!

**Comment by marticliment** [comment]
Hello, please excuse me for the delay in answering, I did not get notified about this thread.

> * I would love a replacement that actually replaces the default Windows clock in the task bar rather than bring its own floating windows.

This cannot be done, and the reasons are explained in the FAQ.


> 2. I would love being able to see something as simple as this:
> 
> ![image](https://user-images.githubusercontent.com/12992190/239760563-113dec62-9fb5-4f4a-a40e-0784f840dfb7.png)

This can be achieved by specifying offsets in a custom format, as explained on https://github.com/marticliment/ElevenClock/pull/1189. For the moment, you will need to have version 4.2.0-beta installed to have this feature. https://github.com/marticliment/ElevenClock/releases/tag/4.2.0-beta
