### ISSUE TITLE
[BUG/ISSUE] Calendar doesn't popup on left click

### ISSUE THREAD

**Issue by Skrell** [marticliment/ElevenClock#1194]
I know this application is for Win11 but I'm using in Win10 and it 95% works great!!  Only thing that seems broken is I can't get the clock to popup the calendar.  It actually does nothing at all when I left-click it after settings and yes I made sure I had the action set to "show calendar" 

Win10x64 22H2 Enterprise

Perhaps you can change the functionality to simply issue the shortcuts key Win+Alt+D upon clicking as that shortcuts works fine to show the calendar.

**Comment by marticliment** [comment]
Windows 10 has a different keyboard shortcut (Win+A) to the notifications pane in Windows 11, which is Win+N

**Comment by Skrell** [comment]
> If you change the clock action to show action center, it will actually pop up the calendar.

where do I change the action to show action center?  I do not see this option.

**Comment by Skrell** [comment]
I tried that but nothing happens when I click it.

**Comment by marticliment** [comment]
Win+A does nothing?

**Comment by marticliment** [comment]
> I wonder if this is bc of a company setting on my laptop? ![image](https://user-images.githubusercontent.com/590266/240305217-6a357c79-66c2-4737-95ee-b57a0bb958bb.png)
> 
> Can you add support perhaps for the Win+Alt+D shortcuts keys which does in fact work on my laptop.

It could, but it shows as enabled
