### ISSUE TITLE
[FEATURE REQUEST] Font/Size/Style different for Date and Time 

### ISSUE THREAD

**Issue by sh0nuff** [marticliment/ElevenClock#1200]
Since the date and time are on two different lines, when I set the font size to 14, so it's easier to read, the spacing is compressed or cut off

I would like to be able to set the font , the size, and style for the date and time separately so that I can have a large time and smaller configuration (and color?) for the date, allowing them to be both readable and discernible  

Apologies if this has already been submitted, I searched before I created the issue

**Comment by marticliment** [comment]
What you should be able to do is to set a custom date and time format, and use html formatting in order to set custom font sizes.
It should work (in theory), but I haven't actually never properly tested it, so I am not sure if it will work at 100%
```
<p style="font-size:14pt;">%H:%M:%S</p>
<p style="font-size:10pt;">%d:%m:%Y</p>
```

Could you please post back your results?
Thanks!

**Comment by marticliment** [comment]
ElevenClock version 4.2.1 will support html text on the clock through custom format
