### ISSUE TITLE
[BUG/ISSUE] tiny horizontal jumps (font width)

### ISSUE THREAD

**Issue by gzotti** [marticliment/ElevenClock#1201]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [ ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug

Just a tiny issue:
I am running clock with seconds. The "1" is narrower than the other ciphers. Whenever second shows a 1, the time string moves right, then left, which is slightly irritating. I can show time centered, but not leftbound, which may be the cheapest solution to at least mitigate this.

## To Reproduce
Steps to reproduce the behaviour:
1. Use custom time format `%#H:%M:%S`
2. Observe for a minute
3. See tiny misbehaviour. 

## Expected behaviour
Clock display (hours, minutes) should not move to the right. Allow leftbound orientation?

## The Log
n/a

**Comment by marticliment** [comment]
Hello,

this issue is caused by the font spacing. You can either set a custom font or restore the original format, which has a mechanism to prevent this.

I'm sorry, but this can¡t be really fixed apart from the _solutions_ avobe.
