### ISSUE TITLE
[BUG/ISSUE] The app shows twice in the toolbar

### ISSUE THREAD

**Issue by hoody4032** [marticliment/ElevenClock#1203]
The app shows twice in the toolbar. One is at the correctly location, the system tray on the right end of the toolbar. The other one covers the startup button on the left end of the toolbar.

OS: win11 version 22H2 (OS Build 22621 1702)
<img width="1275" alt="clock11" src="https://github.com/marticliment/ElevenClock/assets/3246146/441cf61f-60bf-486d-85e7-6b79b47d5810">

**Comment by marticliment** [comment]
Hello, Could it be that you have this setting enabled?
![image](https://github.com/marticliment/ElevenClock/assets/53119851/475c514d-7d56-4dec-9ba5-fc62bf2913eb)

**Comment by hoody4032** [comment]
Yes. If I uncheck this option, it worked fine. Sorry for the late response. Thanks!
