### ISSUE TITLE
The update broke the clock

### ISSUE THREAD

**Issue by ausernamea** [marticliment/ElevenClock#1204]
I loved, loved, loved ElevenClock - specifically for two features. (1) I can display seconds. - Yay! And it still works. (2) Because it does NOT dynamically change the clock in the taskbar when I'm in a new time zone. This broke with the new update. I'm an online teacher and I must keep my computer on U.S. New York time always, always, always, no matter where in the word I am. This way I can keep appointments, Zoom meetings and everything else. I've taught from Stockholm to Washington state and soon to be further west and ElevenClock has been essential. Imagine my dismay this morning to find ElevenClock no longer works correctly for me.

Please please please put this required functionality back.

Thank you.

**Comment by marticliment** [comment]
Hello,

which update broke that?

**Comment by ausernamea** [comment]
Thank you for responding so quickly. Interesting... It worked correctly yesterday (June 27), but not today. I have ElevenClock set for totally silent update so I assumed it updated last night but I just went into Control Panel and see that I am on v4.1.0 which was installed on April 29.  So Hmmm. I wonder what could be going on, It appears my message above is not correct. Now to do some triage (rebooting) and scanning options to see what could be going on. I have to run but I'll get back to you tonight about this.

**Comment by marticliment** [comment]
Can you please try this beta release?
https://github.com/marticliment/ElevenClock/releases/tag/4.2.0-beta

**Comment by ausernamea** [comment]
Marti, For some strange wonderful reason, v4.01 is now working correctly, after a reboot. Yay! I'll give the Beta version a try tonight. As an online teacher I move from place t place so we are leaving Monument Valley (amazing) and going to Arches Natl Park (joyous).

**Comment by ausernamea** [comment]
Marti. v4.20 is now installed. It silently installed over v4.0.1 and is working. Thank you so much for being so responsive. I'll let you know if I see anything amiss. All good for now!
