### ISSUE TITLE
[BUG] Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by areithropos** [marticliment/ElevenClock#1207]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

Windows Defender removed the program with the notification about Trojan:Win32/Wacatac.B!ml. This program is dangerous and executes commands from an attacker.

### Steps to reproduce the issue

Update the program or install it anew

### ElevenClock Log

```text
It got deleted by windows Defender
```

### Relevant information

Happened after I started PC

**Comment by marticliment** [comment]
Hello,

Please file a false positive on Microsoft Defender.

VirusTotal results look fine:
 - https://www.virustotal.com/gui/file/43454b0f1b5ff3935f46743edc2f02f8e4756d890e2faeabd2d8589d79237f67
 - https://www.virustotal.com/gui/file/88c188005c580abb11ab68339945ad9b86bed9ef82657ffd47a60173bec4d383
