### ISSUE TITLE
[BUG] the Notification Badge will block the windows system volume icon

### ISSUE THREAD

**Issue by makusujp** [marticliment/ElevenClock#1209]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

the Notification Badge will block the windows system volume icon

made the reset to default setting is no use.

### ElevenClock Log

```text
log file is too long, attached as txt
```

### Screenshots and videos

![snap7540](https://github.com/marticliment/ElevenClock/assets/44157839/2bf77e95-5697-40f9-bc63-da0ac98d18aa)
![snap7541](https://github.com/marticliment/ElevenClock/assets/44157839/05002cf3-1b0e-4dac-9fcc-5b6d40164049)
[log.txt](https://github.com/marticliment/ElevenClock/files/11915063/log.txt)

**Comment by marticliment** [comment]
Hello, 

I suppose you are running a beta version of Windows 11, right?

**Comment by Seeloewen** [comment]
Same issue here with no beta version, I'm running Windows 11 22H2 22621.1848

**Comment by marticliment** [comment]
> 22621.1848

But you are on Windows Insider, right?

**Comment by laszlodrgero** [comment]
Same error. I don't use the beta version and I'm not an insider. I am using the latest windows 11. Windows 11 Pro 22H2 22621.1928

**Comment by Seeloewen** [comment]
> > 22621.1848
> 
> But you are on Windows Insider, right?

Nope, I'm not. Just updated to 22621.1928 (not insider) and issue persists

**Comment by chauhanvaibhav92** [comment]
Hello, I am also on Microsoft Windows [Version 10.0.22621.1928], non-beta, non-Insider build and am experiencing the same issue with the 4.2.0 version! The volume icon get completely obscured.

**Comment by Nekrux** [comment]
Same here. I noticed this tho… As soon as I receive a new notification Eleven Clock doesn't hide the volume icon while when there are no notifications the bug appears. Not a big problem for me, since I'm using EarTrumpet, but my OCD says nope.

![d0TJMKuFXT](https://github.com/marticliment/ElevenClock/assets/11512054/4065c799-0b47-46cb-b2c5-a797e62f0aa6)
![r6hK6FKyn2](https://github.com/marticliment/ElevenClock/assets/11512054/d99980d1-e3b1-4a16-9e41-97ed5b5f847e)

**Comment by marticliment** [comment]
All rigit, it looks like I got the build number wrong.

I will fix this soon

**Comment by marticliment** [comment]
This issue will be fixed on version 4.2.1
