### ISSUE TITLE
[FEATURE REQUEST] (package manager support (winget, chocolatey, scoop))

### ISSUE THREAD

**Issue by devbytemehedi** [marticliment/ElevenClock#1215]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

[Winget ](https://winget.run) Comes with preinstalled in windows now so if i could install this package with a package manager like winget or choco or scoop that would be great.

#### Examples
 
`winget install elevenclock` 
or
 `choco install elevenclock`
or
 `scoop install elevenclock`

### Describe how this new feature could help users.

This will help users to easily install this package for new users who have go through [releases ](https://github.com/marticliment/ElevenClock/releases) page or have problems with **microsoft store**.
and it will be help this package to find new users and new users means more feedback.

**Comment by marticliment** [comment]
you can actually install ElevenClock from winget and from Chocolatey:

`winget install ElevenClock --source winget`
`winget install ElevenClock --source msstore`
`choco install elevenclock`

**Comment by marticliment** [comment]
I have added those commands to the readme

**Comment by devbytemehedi** [comment]
thank you 😁.
