### ISSUE TITLE
add ordinals to dates.  For example 21st or 3rd

### ISSUE THREAD

**Issue by manglewurzle** [marticliment/ElevenClock#1231]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

I would like to have the option to add ordinals to dates so that 21 Jul, or 21 July appeared as 21st Jul or 21st July

### Describe how this new feature could help users.

It matches the way we normally describe dates

**Comment by marticliment** [comment]
Hello @manglewurzle,

I am afraid this is not supported by the 1989 C standard, so it can't be implemented.

**Comment by manglewurzle** [comment]
Good and informative answer.  Thankyou.

Martin
