### ISSUE TITLE
[BUG] Elevenclock shows dark text color on white wallpapers

### ISSUE THREAD

**Issue by Dhyfer1** [marticliment/ElevenClock#1233]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

Hi @marticliment 

The text color for the custom clock is always white for any wallpaper, except for wallpapers that have white in the taskbar area.

![image_3](https://github.com/marticliment/ElevenClock/assets/50301201/0ffb79e2-e1aa-4d3e-a761-62cfca0fd7e2)

As you can see in the image above, for the custom clock in the left corner as well as for the date in the right corner, the text color automatically changes to black when I leave the wallpaper you already saw. I should clarify that I have never touched the setting _Use a custom font color_ in Elevenclock settings>Clock Appearance 

### Steps to reproduce the issue

Just try any white image, the desktop image is the Bing image of the day for today, August 1, which you can see [here](https://bingwallpaper.anerg.com/detail/us/DenaliClimber). 

### ElevenClock Log

```text
N/A
```

### Relevant information

In version 4.0.4, in Elevenclock settings>Clock Appearance there was a setting named:

![image_4](https://github.com/marticliment/ElevenClock/assets/50301201/f8aecbe6-5ed5-4076-9ab1-dc14cc6e72ce)

which is enabled by default. When the wallpaper is white, and when this setting is unchecked, the custom clock text color automatically changes from black to white, and remains white even on white wallpapers.

The setting you saw disappeared from version 4.1.0 onwards, I suggest you bring that setting back.

**Comment by marticliment** [comment]
this feature will be disabled if you set a custom clock text color.

**Comment by Dhyfer1** [comment]
Hi. 

If the setting I showed in the second image was still there, and which I said was removed from version 4.1.0 onwards, it would certainly have helped me to change the color of the clock text without the need to touch the setting _Use a custom font color_ in Appearance.

But even after choosing a custom color in _Use a custom font color_ there is no visible change to the taskbar clock, and the selected color is only visible within Elevenclock Appearance settings.

I have reinstalled elevenclock, but it is still not possible to change the color of the text. I have attached log.

[log.txt](https://github.com/marticliment/ElevenClock/files/12240788/log.txt)

**Comment by marticliment** [comment]
This issue has been fixed. The fix will be available with the next ElevenClock version

**Comment by Dhyfer1** [comment]
Thank you.  I hope the next version will come soon. 😊

**Comment by marticliment** [comment]
New version available on GitHub

**Comment by Dhyfer1** [comment]
> New version available on GitHub

Thank you so much. This version already fixes the text color bug. Now I can change the color :)
