### ISSUE TITLE
Tolgee translation review - Unable to review my own translations

### ISSUE THREAD

**Issue by norway-yv** [marticliment/ElevenClock#1245]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Could you bring back the old system for reviewing translations in Tolgee? Now, I cannot review my own translations anymore. This will most likely lead to a constantly growing percentage of Norwegian translations only being "translated" and not "reviewed", because I (as far as I know) am the only active contributor to the Norwegian translations. 

### Describe how this improvement could help users.

This would be useful in cases with small languages (like Norwegian), where there are no more translators that can review each others' translations.

**Comment by marticliment** [comment]
Done!
