### ISSUE TITLE
Is week number ISO? 

### ISSUE THREAD

**Issue by jerry1970** [marticliment/ElevenClock#1249]
Is the week number following common ISO or the lesser used US logic?

**Comment by marticliment** [comment]
More info: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes:


```
Weekday as a decimal number, where 0 is Sunday and 6 is Saturday.
```

**Comment by jerry1970** [comment]
I asked about week number, not week day...

**Comment by marticliment** [comment]
![image](https://github.com/marticliment/ElevenClock/assets/53119851/6a4f598b-f86d-412f-b254-0b4928e1d7f9)

**Comment by jerry1970** [comment]
Ah thanks. I wss afraid of that. That is no ISO week number.
Without ISO week number or will be useless in a large part of the world outside the USA.

**Comment by MaaxGr** [comment]
Hi, 

neither `%U` nor `%W` are aligned with the ISO 8601 week number standard, see [[Microsoft Power Fx documentation](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-weeknum)](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-weeknum) for example.

At the moment ElevenClock says that i'm in calendar week 1, but week 2 would be correct according to ISO standard.
Could you look into that again @jerry1970?


Kind Regards 
Max

**Comment by jerry1970** [comment]
We are in week 2 now (Tuesday 7 January 2025), yes. Week 2 started yesterday, Monday 6 January.

I got a new job and they let us use Windows 10, fortunately, so I am back to T-Clock, which has an ISO week number. Glad to be on W10 instead of W11 for many reasons. Hope I can go to Ubuntu soon.

**Comment by marticliment** [comment]
If you wish, ElevenClock allows custom date and time formats where you can specify date and time offsets:
`{%v+1}`

**Comment by jerry1970** [comment]
> If you wish, ElevenClock allows custom date and time formats where you can specify offsets: `{%v+1}`

Offsets as in hours from UTC? Then you'd have to change that at every change in DST.
Or offsets in week numbers? Then you might need to change that every year.

**Comment by marticliment** [comment]
You are able to set a custom date and time format, and for each token (which can be hours, seconds, or any other token that is a number) you can specify a numeric offset to it. On ElevenClock settings you will find more information about it when enabling the "Set a custom date and time format", under Date and time preferences

**Comment by MaaxGr** [comment]
Hey @jerry1970,
i probably found the solution.

Just use
- **`%V` if you want the calendar week in ISO 8601 (european) format** ❗
- `%U`  if you want the calendar week in american format (Sunday as the first day of the week)
- `%W` if you want the calendar week in american format (Monday as the first day of the week)

That is probably the better solution than using an offset 😅 @marticliment 


Reference: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

**Comment by jerry1970** [comment]
> That is probably the better solution than using an offset 😅 @marticliment

If that works then that is the best solution indeed, good one!
I'll remember it in case I am forced to work with Win11.
