### ISSUE TITLE
[BUG] Clock broken on HiDPI

### ISSUE THREAD

**Issue by kconover** [marticliment/ElevenClock#1261]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

Using on my laptop (Lenovo X1 Carbon 11th generation with OLED screen), 2800x1800 at 225% scale, and taskbar set to autohide. Clock autohides only when my mouse is in the top half of the screen. Suspect a misplaced decimal point. Thanks!

### Steps to reproduce the issue

Just use the laptop with clock enabled. 

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0520024299621582 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.3.0 (v4.3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 255,255,255,100.0
🟢 Regular sized taskbar
🟡 ElevenClock set to hide with the taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1080, 754, 200, 46)
🔵 Full screen rect:  (0, 0, 1280, 800)
🟡 Using custom font color: 255,0,0
🔵 Font families   : []
🔵 Custom font     : ScalaSansOT-Black,12,-1,5,900,0,0,0,0,0,0,0,0,0,0,1,Black
🔵 Font size: 12.0
🔵 Language file up-to-date
🟡 Custom loaded date time format (clock 0): %H%M\n%a %#m/%#d
🟢 Loaded clocks in 5.222606658935547
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 130, in __init__

🔴   File ".\settings.py", line 130, in __init__

🔴 UnboundLocalError: cannot access local variable 'langName' where it is not associated with a value

🔴 UnboundLocalError: cannot access local variable 'langName' where it is not associated with a value

🔴 Note this traceback was caught by reporter and has been added to the log (cannot access local variable 'langName' where it is not associated with a value)
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 11.492523193359375
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 255,255,255,100.0
🟢 Regular sized taskbar
🟡 ElevenClock set to hide with the taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1080, 754, 200, 46)
🔵 Full screen rect:  (0, 0, 1280, 800)
🟡 Using custom font color: 255,0,0
🔵 Font families   : []
🔵 Custom font     : ScalaSansOT-Black,12,-1,5,900,0,0,0,0,0,0,0,0,0,0,1,Black
🔵 Font size: 12.0
🟡 Custom loaded date time format (clock 0): %H%M\n%a %#m/%#d
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Restart loop: 1
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Copying log to the clipboard...
```

**Comment by marticliment** [comment]
Hello,

Please navigate to C:\Users\<user>\AppData\Local\Programs\ElevenClock, right-click ElevenClock.exe and select properties
Then, under the Compatibility tab, select "Open elevated PPP settings", then select "Invalidate the behaviour of high PPP." and test out the three options to see if one of them works

![image](https://github.com/marticliment/ElevenClock/assets/53119851/f6dffa04-7527-4fa8-921f-ecc27965a50f)

**Comment by marticliment** [comment]
Hello @kconover, thanks for your answer.

You may want to leave ElevenClock with this configuration while I will investigate this issue.

**Comment by kconover** [comment]
Will do. Thanks very much!

--Keith

Keith Conover, M.D., FACEP, FASRC
Clinical Associate Professor, Emergency Medicine,
University of Pittsburgh School of Medicine
www.conovers.org<http://www.conovers.org/>

**Comment by kconover** [comment]
Also, I just found out that with ElevenClock in this mode, when I run the mouse cursor to the bottom right and click to show the desktop (clear the desktop) which used to work, it doesn't work. Sometimes it shows me a little popup above ElevenClock that says "Show Desktop" but clicking it doesn't work.

Thanks for such a great clock! Love it!

--Keith

Keith Conover, M.D., FACEP, FASRC
Clinical Associate Professor, Emergency Medicine,
University of Pittsburgh School of Medicine
www.conovers.org<http://www.conovers.org/>

From: Conover, Keith ***@***.***>
Sent: Thursday, September 28, 2023 13:47
To: marticliment/ElevenClock ***@***.***>
Cc: Conover, Keith ***@***.***>
Subject: RE: [marticliment/ElevenClock] [BUG] Clock broken on HiDPI (Issue #1261)

Will do. Thanks very much!

--Keith

Keith Conover, M.D., FACEP, FASRC
Clinical Associate Professor, Emergency Medicine,
University of Pittsburgh School of Medicine
www.conovers.org<http://www.conovers.org/>

**Comment by marticliment** [comment]
You can enable this feature from the settings window:
![image](https://github.com/marticliment/ElevenClock/assets/53119851/a9343422-3452-4ccd-b298-fd3419bc0f2b)

**Comment by kconover** [comment]
Great! Except that it's hard to get to the ElevenClock settings on my laptop with current settings. On my desktop workstation with Taskbar Autohide off, I can right-click the clock and access the settings.

On my laptop, with Taskbar Autohide on and the ElevenClock Compatibility set to System (enhanced), I can't right-click (or left-click) the clock to access the ElevenClock menu including Settings.

Sorry to be such a pest.

--Keith

Keith Conover, M.D., FACEP, FASRC
Clinical Associate Professor, Emergency Medicine,
  University of Pittsburgh School of Medicine

**Comment by marticliment** [comment]
> On my laptop, with Taskbar Autohide on and the ElevenClock Compatibility set to System (enhanced), I can't right-click (or left-click) the clock to access the ElevenClock menu including Settings

You should have a shortcut on your start menu to access settings:
![image](https://github.com/marticliment/ElevenClock/assets/53119851/d9ac51fa-2724-4555-8dbd-5247fef188a1)

**Comment by kconover** [comment]
I did find the Settings there, thank you!

However, the "Add the "Show Desktop" button on the right side of each clock did not show a "Show Desktop" button, even after a reboot.

I also tried "Change the action done when the clock is clicked" to "Show desktop" and that didn't work, either.

Sigh.

Again, sorry to keep bothering you.

--Keith

Keith Conover, M.D., FACEP, FASRC
Clinical Associate Professor, Emergency Medicine,
  University of Pittsburgh School of Medicine

**Comment by marticliment** [comment]
Hello @kconover,

Can you please try adjusting horizontal clock position to the left and see if you can get the Show Desktop button to show when hovered.

I understand that clicking the clock will trigger the notifications pane, right?

![image](https://github.com/marticliment/ElevenClock/assets/53119851/95a107e2-76c6-4191-9b3a-26f55d7689ca)

**Comment by kconover** [comment]
OK, I tried moving the clock to the left, with very strange results. My customized clock (red on white, custom font) moved to the left, but what looked like a default clock of red on black still showed in the bottom right, even after rebooting. But it was stuck at 00:00 AM 00/00/0000. Maybe it's a zombie clock in honor of approaching Halloween? And no "show desktop" nor did a click in the bottom right show the desktop.

--Keith

Keith Conover, M.D., FACEP, FASRC
Clinical Associate Professor, Emergency Medicine,
  University of Pittsburgh School of Medicine

**Comment by marticliment** [comment]
Can you please send me a screenshot of it and your logs now with the clock moved?

I don't understand why is this happening.

**Comment by kconover** [comment]
OK, now with the log attached. Sorry.

--Keith

Keith Conover, M.D., FACEP, FASRC
Clinical Associate Professor, Emergency Medicine,
  University of Pittsburgh School of Medicine

From: Conover, Keith ***@***.***>
Sent: Wednesday, October 11, 2023 3:01 PM
To: marticliment/ElevenClock ***@***.***>
Cc: Conover, Keith ***@***.***>
Subject: RE: [marticliment/ElevenClock] [BUG] Clock broken on HiDPI (Issue #1261)

Attached.

--Keith

Keith Conover, M.D., FACEP, FASRC
Clinical Associate Professor, Emergency Medicine,
University of Pittsburgh School of Medicine
www.conovers.org<http://www.conovers.org/>

**Comment by marticliment** [comment]
Hello, I think your ElevenClock installation is broken.

Please uninstall ElevenClock, delete a folder named .elevenclock placed on your user directory and then reinstall ElevenClock from the Microsoft Store.

Thanks!

**Comment by marticliment** [comment]
The issue with autohiding has been fixed, and changes will be effective once the next ElevenClock version gets published.

Then, please do uninstall and reset ElevenClock to make sure no weird things happen from the _modified_ last version to this new one.
