### ISSUE TITLE
[BUG] Support newer win32mica versions

### ISSUE THREAD

**Issue by arshanskiyav** [marticliment/ElevenClock#1280]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

Hi

I want to add my own functionality, but after building the application does not start.
I get the error "Unable to get import name 'Micamode' from 'win32mica'."
I checked this and found that in the latest version "Micamode" has been renamed to "Micathema".

I tried to run the application without my own changes and build, but I had the same problem. 

I replaced "micamode" with "micathema". I assembled it and the application launched.
But the Settings window does not open.
The clock window on the taskbar has closed, but the process is not closed and the amount of allocated memory is growing.

Then I replaced the "requirements.txt" versions with:

> PyInstaller==5.9.0
> PySide6==6.5.2
> keyboard
> psutil==5.9.1
> pytz==2023.3
> win32mica==2.0
> winshell
> pypiwin32

### Steps to reproduce the issue

Python version 3.11.3/3.10.11

`git clone https://github.com/martinet101/ElevenClock && cd elevenclock`
`pip install -r ./requirements.txt`
`python __init__.py`

### ElevenClock Log

```text
Application does not start
```

### Relevant information

I checked it on my laptop and on a new virtual machine with Windows 10

**Comment by marticliment** [comment]
Please downgrade win32mica to version 2.0, and if it does not work downgrade to 1.8. Win32mica 1.8 will work for sure

**Comment by arshanskiyav** [comment]
> Please downgrade win32mica to version 2.0, and if it does not work downgrade to 1.8. Win32mica 1.8 will work for sure

I already did it, thanks

**Comment by marticliment** [comment]
Done!
