### ISSUE TITLE
Blacklist this monitor : wrong monitor blacklisted after reboot

### ISSUE THREAD

**Issue by micheldiemer** [marticliment/ElevenClock#1290]
I have three monitors, blacklisted two of them. ElevenClock is displayed on the main monitor, that's fine.

Reboot the computer. ElevenClock is on the second monitor, not on the main monitor.

I want ElevenClock to be on the left of my taskbar and nowhere else. My taskbar is only on the main monitor.

**Comment by marticliment** [comment]
I will restore the "Show only on main monitor" setting

**Comment by micheldiemer** [comment]
In december you have marked this issue as "ready-to-go". When will you restore this setting on the main branch ?

**Comment by marticliment** [comment]
Hello,

I am afraid that due to some recent changes in my life, my priorities have changed, and ElevenClock is not one of them anymore, or at least for the time being.

**Comment by jayPare** [comment]
@marticliment is the change in a PR? Maybe I can help review it?

**Comment by marticliment** [comment]
There is no PR for this yet. ElevenClock uses Qt to detect monitors, and it looks as if Qt was misreporting the displays, for what there is no fix unless Qt fixes it
