### ISSUE TITLE
[CRASH] (Enter your description here)Initially works then it doesm't

### ISSUE THREAD

**Issue by NBspaceCadet360** [marticliment/ElevenClock#1291]
### Please confirm these before moving forward

- [X] I have tried reinstalling ElevenClock
- [X] I have tried resetting ElevenClock by reinstalling it and selecting the "Clean Install" option.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).

### Describe your crash

I have Windows 11 Version 10.0.22621 Build 22621 and this app has stopped working.
A pop up says it is incompatible with Windows. Re-install doesn't work and there seems to be no updating.
Avoid this dud.

### Logs (if possible)

```text
pop up:  "This program does not support the version of Windows your computer is running"
```

### More details

This worked well for about 6 months. Then alert box city.

**Comment by marticliment** [comment]
Can you please share a screenshot of the message box?

**Comment by NBspaceCadet360** [comment]
OK -  
![alert](https://github.com/marticliment/ElevenClock/assets/28228292/9171b0d7-af36-40b3-8c8f-8b3ecee9349c)

this appeared less than 60 seconds after re-install.

**Comment by NBspaceCadet360** [comment]
I like the clock look so I tried many options, sync, restart etc.

**Comment by marticliment** [comment]
Please do try:
1. Uninstall ElevenClock
2. remove a folder named .elevenclock, located under your user directory.
3. perform a [health check](https://www.windowscentral.com/how-use-dism-command-line-utility-repair-windows-10-image)
4. Reinstall ElevenClock from the microsoft store.

Let me know if the steps above do work.

**Comment by NBspaceCadet360** [comment]
on step 3 I got this 
![cmd](https://github.com/marticliment/ElevenClock/assets/28228292/7241cf51-123c-48b2-88f8-e59e57da0a4b)

**Comment by NBspaceCadet360** [comment]
.... and alert box quickly shows ....   meanwhile I will remove it again ....

**Comment by marticliment** [comment]
> on step 3 I got this ![cmd](https://private-user-images.githubusercontent.com/28228292/288217290-7241cf51-123c-48b2-88f8-e59e57da0a4b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MTQ3MzcsIm5iZiI6MTcwMTgxNDQzNywicGF0aCI6Ii8yODIyODI5Mi8yODgyMTcyOTAtNzI0MWNmNTEtMTIzYy00OGIyLTg4ZjgtZTU5ZTU3ZGEwYTRiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDIyMTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyODUwYmU1NTA5ZTViM2I5ZTg1NzVlNDM1MDRjZmRhZDBjODUyMzE3MDQ5YWMzZjhhZDgzMjdjMDRmOTk5ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B8QYHV9w3R131rTRys24SBFlMNMeP4-Djj_o3Atcylw)

please do run those commands as administrator

**Comment by NBspaceCadet360** [comment]
eff .... alert box came up after re-install and new command prompt -
![cmd2](https://github.com/marticliment/ElevenClock/assets/28228292/22e34b86-9d7e-45bd-8907-a8eaea06d8c9)

**Comment by marticliment** [comment]
I am afraid I don't know what is happening here: ElevenClock's source code does not have any version check, so this should be caused by Windows itself.

Can you please share your system specifications?

Btw, do older versions of ElevenClock work?

**Comment by NBspaceCadet360** [comment]
OS Name	Microsoft Windows 11 Home
Version	10.0.22621 Build 22621
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	GPU Company
System Model	GWTN156-7
System Type	x64-based PC
System SKU	0000000000000000
Processor	11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz, 2995 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	GPU Company CC-BI-15.6-N14TBR310-TB60A-231-C, 9/16/2021
SMBIOS Version	3.3
Embedded Controller Version	1.04
BIOS Mode	UEFI
BaseBoard Manufacturer	GPU Company
BaseBoard Product	GPU Company
BaseBoard Version	Default string
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22621.2506"
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.75 GB
Available Physical Memory	928 MB
Total Virtual Memory	16.7 GB
Available Virtual Memory	4.04 GB
Page File Space	9.00 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualization-based security	Not enabled
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Off
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

-----------------------
I don't have older versions.  I used to like saythetime.com ap but Windows wrecked it with Windows 11.

**Comment by marticliment** [comment]
but if you install an older version does it with then?

**Comment by NBspaceCadet360** [comment]
I will try  ver. 4.3.1    ,,,,  but the installer can't be opened because of MSN smart screen.
When I go to task mgr to turn off smart screen it turns itself back on.

Should I go to Device Security and disable Secure Boot?

**Comment by marticliment** [comment]
No, Secure Boot doesn't have anything to do with the AV...

Try installing ElevenClock version 4.3.2 and 4.3.3, and post here the results
