### ISSUE TITLE
Calendar still popsup only on primary monitor

### ISSUE THREAD

**Issue by fippy** [marticliment/ElevenClock#1303]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Hi, unless I'm mistaken, I can't find a way to pop the calendar up on the monitor where the clock is clicked. It's HIGHLY confusing that it popsup only on the primary monitor. Hopefully a fix is possible?

### Describe how this improvement could help users.

It would avoid confusion.

**Comment by marticliment** [comment]
This is a Windows 11 limitation.

If you press <kbd>Win+N</KBD> with your mouse on a secondary screen the calendar still pops on the primary display.
