### ISSUE TITLE
[FEATURE REQUEST] Add option to change how week numbers are calculated

### ISSUE THREAD

**Issue by yrjarv** [marticliment/ElevenClock#1304]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

I would love to have an option, perhaps under "Date & Time Settings", to choose how the week numbers are calculated. Currently, the first week of January is week 0. That does not follow the ISO 8601 standard, which most of Europe (in my experience) uses. My proposal is to have a dropdown menu with a few options, including the one that is used today and ISO 8601-compliant week numbering.

### Describe how this new feature could help users.

In many countries, the first-week-is-week-0 system is not standard, leading to the week numbering no longer being useful. If my proposed feature, the user would be able to be in sync with the rest of the world in terms of which week they are in.

**Comment by marticliment** [comment]
ElevenClock relies on https://strftime.org/ reference to format date and time. If the element you are searching is not there, I'm afraid it will not be compatible with ElevenClock.
However, I think the tag you are looking for may be`%W` instead of `U`.

**Comment by yrjarv** [comment]
That seems to work, thank you for the quick reply
