### ISSUE TITLE
[BUG] Incorrect Week-Number calculation in 2024

### ISSUE THREAD

**Issue by asafhas** [marticliment/ElevenClock#1306]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

Starting from 1-Jan-2024 the Week-Number calculation for Sunday-base weeks is wrong.
Example:
 - On Sunday, 14-Jan:
     - The value of "%U" was "02" - Should be "03".
     - The value of "%W" was "02" - OK.
 - On Monday, 15-Jan:
     - The value of "%U" was "02" - Should be "03".
     - The value of "%W" was "03" - OK.  

 A few smaller issues:
 - When using the format "{%U+1}" to bypass the issue above, it shows "3" instead of "03".
 - The following formats (mentioned in https://strftime.org/) are not working in the app: "%-U" and "%-W".

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.003030061721801758 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.3.3 (v4.33) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1154, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1200)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🟡 Desktop button enabled
🟡 Custom loaded date time format (clock 0): WW{%U+1} %H:%M\n%x
🟢 Loaded clocks in 0.7490260601043701
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1154, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1200)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🟡 Desktop button enabled
🟡 Custom loaded date time format (clock 0): WW{%U+1} %H:%M\n%x
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, DisableNotifications:True
🟢 Loaded everything in 3.423731803894043
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1154, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1200)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Restart loop: 2
🟡 Desktop button enabled
🟡 Custom loaded date time format (clock 0): WW{%U+1} %H:%M\n%x
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Showing tooltip
🔵 Short date string: HH:mm
🔵 TZ 1 is America/Los_Angeles
🔵 Long date string: dddd, MMMM dd, yyyy
🔵 Copying log to the clipboard...
```

### Relevant information

During 2023 the calculation was correct.

**Comment by yrjarv** [comment]
Maybe you can get a few answers in #1304 even though the two issues are different?

**Comment by asafhas** [comment]
I saw it, but it's a different issue. Thanks!

**Comment by marticliment** [comment]
> * The following formats (mentioned in https://strftime.org/) are not working in the app: "%-U" and "%-W".

Try replacing the `-` for a hashtag `#`. Dash is for unix/linux, hashtag is for windows

**Comment by yrjarv** [comment]
Sorry that I am "hijacking" this thread, but to me it seems like the attached image would contain the week numbers as per strftime.org's documentation. Week 0 is before the first Sunday, then comes W1 - which might not be how everyone calculates week numbers but unfortunately how strftime does it.
![Untitled](https://github.com/marticliment/ElevenClock/assets/94965821/41805fba-c92a-4edd-a687-060141714bf9)

**Comment by asafhas** [comment]
During weekdays (let's put aside Sunday), both %U and %W should give the same value. But they are not.
Today, Wednesday 17-Jan-2024, %U shows "02" and %W shows "03".
BTW, according to this ISO Week calculator, the correct value is "03": https://myweb.ecu.edu/mccartyr/isowdcal.html

**Comment by yrjarv** [comment]
If my understanding of the %U tag is correct, it counts from the first Sunday of a year (7th of January counts as the first day of week 1), but ISO (and %W) counts week 1 as the first week with 4 or more days that are all in the same year.
So, if the year starts on Monday, %W would count week 1 from the following Sunday while %U should count from the Monday where the year starts.
In terms of the ISO Week calculator, it counts the same way as %W - in compliance with ISO standards. According to strftime.org the following applies for %U:

> All days in a new year preceding the first Sunday are considered to be in week 0.

Now I might of course be wrong about this, or might just have misinterpreted your issue. But I am pretty sure that it is working as intended.

**Comment by marticliment** [comment]
> BTW, according to this ISO Week calculator, the correct value is "03": https://myweb.ecu.edu/mccartyr/isowdcal.html

The issue here is that there is not _one_ ISO only, Python strftime uses ISO 8601 (which is inherited from C 1989 Standard, and used across many other programming languages, even the strftime linux command uses it) while your website does not report on which ISO is based.

I am afraid ElevenClock (which uses strftime functions) is not reporting an incorrect week day, but rather it provides the one from the C89/ISO, which does not coincide with the format you are used to, and with the unspecified-iso week calculator

**Comment by asafhas** [comment]
Indeed, it looks like Python lib is printing "02" when using "%U" today.
It is still strange that for half of the world (according to this [site](https://www.timeanddate.com/calendar/days/first-day-of-the-week.html)) we are in Week-02, and for the other half we are in Week-03. But this is not a problem of this application.

For our purpose, what is the correct way to print "03" (and not "3") with a manual adjust of the value {%U+1}?

**Comment by marticliment** [comment]
I am afraid this is not possible right now, since {%U+-i} parses %U as an integer and then adds/subtracts the i offset, without taking formatting into account. You may want to hard-code a zero until we reach week 10, and then remove this zero.

**Comment by asafhas** [comment]
I understand.
Thank you for the quick response. You can close this issue now.
