### ISSUE TITLE
[BUG] clock getting disbaled

### ISSUE THREAD

**Issue by YashSoPro** [marticliment/ElevenClock#1321]
### Please confirm these before moving forward

- [ ] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

Okay, so the issue I'm having is with the Elevnclock app. Whenever I click on the battery icon, which is also where I connect/disconnect my earbuds and adjust the volume, Elevnclock gets disabled. How do I fix this?

### Steps to reproduce the issue

Click the clock icon in the system tray to disable/enable the 12-hour clock.

### ElevenClock Log

```text
i dont know how to do this not working for me
```

### Relevant information

no

### Screenshots and videos

if you need i can create because if have to install things

**Comment by marticliment** [comment]
When clicking out of the taskbar, does ElevenClock reappear?

**Comment by YashSoPro** [comment]
> When clicking out of the taskbar, does ElevenClock reappear?

it does but it doesn't match if you could fix it please try ti fix

**Comment by marticliment** [comment]
I am sorry, but this is an unfixable known bug, caused by the way in which ElevenClock works
