### ISSUE TITLE
[ENHANCEMENT] allow copilot icon (or anything else that windows puts to the right of the clock) between the clock and the 'show desktop' button

### ISSUE THREAD

**Issue by mxndtaylor** [marticliment/ElevenClock#1322]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

With microsoft copilot in preview state, I've noticed that elevenclock was covering it up:
![image](https://github.com/marticliment/ElevenClock/assets/20446657/125228ac-7b6d-4aef-ab5a-08678ddc5cd8)

So, I manually adjusted the position of the clock so that it's more in line with the new position of the taskbar clock.
-41 horizontal is what I ended up going with:
![image](https://github.com/marticliment/ElevenClock/assets/20446657/2eb673df-1f4c-41b9-9891-b01e51d8d8ea)

But you can see it's still clipping the copilot icon. With my mouse over the copilot icon so you can see the cutoff more clearly:
![image](https://github.com/marticliment/ElevenClock/assets/20446657/83cb8fbc-456d-4fa4-9575-94a669fb870f)

If I move it further left, it starts covering up the power/volume/wifi icons.
Here it is at -48:
![image](https://github.com/marticliment/ElevenClock/assets/20446657/2be980ee-2eb5-48bc-a295-822ce3495eb8)

I _do_ have the 'show desktop button' setting enabled in the screenshots, but I've tried it both both ways, and it's not any different.

Since the main reason I installed elevenclock was to have the show desktop icon in the bottom right corner of all my screens, this is really annoying.

So, my suggestion is to do one of: 
- duplicate the copilot button on elevenclock ui if it's existing on the machine  
- add an option to interdependently custom the position of the 'show desktop' button
- add an option to 'lock' the 'show desktop' to a custom corner of each screen - the user would choose TR, TL, BR, BL corner for each screen or just one option for all screens

### Describe how this improvement could help users.

This would allow users to keep the copilot icon easily accessible without having to sacrifice having the show desktop button in the corner of their screen.

**Comment by marticliment** [comment]
I will study this, but I don't know how I am going to get this working, on EU there is no copilot button available...

**Comment by mxndtaylor** [comment]
Oh... yeah that would make it difficult to test any solution.

Well, I can offer to test it myself if you come up with something, time permitting.

I thought it might be useful to see where the clock is hitting in relation to copilot icon with the elevenclock raised up a bit, at least this should give an idea of where it is in relation to the other components:
![image](https://github.com/marticliment/ElevenClock/assets/20446657/c3f3820f-633a-42c5-874b-eb81ccc1c898)

Hopefully that helps a bit?

**Comment by marticliment** [comment]
The issue here is that I don't only need to understand the visual layout, but I also need to be able to undertstand the interactivity, the hitboxes, the scale/theme changes, when copilot is shown and when not, how to trigger copilot when the clock is clicked, etc.

I am afraid that I will not be able to add MS Copilot support until I can experience the taskbar icon myself

**Comment by TechySC23** [comment]
@marticliment Just follow steps:
1. Go to settings and then go to Time & Language.
2. Then Language and region
3. Then select the country or region option and set it to something other than EU countries like US, India, Brazil, etc. But keep in mind if it changes the regional format then just adjust the option below it.
Simple and easy.
Also turn the location service off if it doesn't work.

**Comment by TechySC23** [comment]
And oh well........ The copilot is by default in besides the Start button in "Normal" Windows. But @mxndtaylor machine has "Insider" Windows so the copilot is in that version. I think that there is a 50% chance that it will come in Normal Windows. And 50% not to come.

**Comment by marticliment** [comment]
> @marticliment Just follow steps:
> 
> 1. Go to settings and then go to Time & Language.
> 2. Then Language and region
> 3. Then select the country or region option and set it to something other than EU countries like US, India, Brazil, etc. (Something that is in the Copilot availability list). But keep in mind if it changes the regional format then just adjust the option below it.
>    Simple and easy.
>    Also turn the location service off if it doesn't work.

I am afraid it is not that easy... I had already tried in the past to get copilot, but it still does not work

**Comment by TechySC23** [comment]
> > @marticliment Just follow steps:
> > 
> > 1. Go to settings and then go to Time & Language.
> > 2. Then Language and region
> > 3. Then select the country or region option and set it to something other than EU countries like US, India, Brazil, etc. (Something that is in the Copilot availability list). But keep in mind if it changes the regional format then just adjust the option below it.
> >    Simple and easy.
> >    Also turn the location service off if it doesn't work.
> 
> I am afraid it is not that easy... I had already tried in the past to get copilot, but it still does not work

Doesn't? Oh well. Windows or Microsoft Limitation....... Wait what about VPN's?

**Comment by marticliment** [comment]
> Wait what about VPN's?

Also tried.

**Comment by TechySC23** [comment]
Think so. BTW your clock was great but my machine had some problems so had to uninstall it😔

**Comment by iainwyatt** [comment]
I'm not on an insider build, and this week I couldn't figure out why I couldn't see the copilot icon anymore - then realised it has moved to the bottom right and ElevenClock was hiding it!!! :( I use the clock on the left side anyway (I don't use widgets) so ticking the option for "Disable hiding the default windows clock" works for me for now.
