### ISSUE TITLE
[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by Cypherthegreat** [marticliment/ElevenClock#1326]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

Hi, Thank you for your work on this project however I am currently having an issue.

I have a triple monitor setup, 1 vertical screen on the left 2 horizontal centre and right.
Currently 11clock is sometimes working on a single monitor or non at all. 
In the screenshot provided, it is currently not running on any monitor.
Randomly it will work on all of them or just stop again its strange to say the least.
I have attached a log when it is not working and a second log which has all 3 working.

I am using win11.
the format I am using is
%H:%M:%S
%a %d/%m/%y
Thank you for your assistance

### ElevenClock Log

```text
see attached
```

### Relevant information

[11clock log.txt](https://github.com/marticliment/ElevenClock/files/14574588/11clock.log.txt)
[11clock log working.txt](https://github.com/marticliment/ElevenClock/files/14574590/11clock.log.working.txt)

### Screenshots and videos

![image](https://github.com/marticliment/ElevenClock/assets/29981993/0d48fa8c-bb0f-4f36-847e-cf399f317c4d)
![image](https://github.com/marticliment/ElevenClock/assets/29981993/b12e6aa6-4cee-4e99-bbf9-a96272272e14)
![image](https://github.com/marticliment/ElevenClock/assets/29981993/cadea7a2-1204-4ee3-849f-5fb5500ffcf8)

**Comment by marticliment** [comment]
Hello,

Are you using any kind if software such as screen recorders, game overlays (for example nvidia overlay) or any other software thay may capture/render the whole screen?

**Comment by Cypherthegreat** [comment]
> Hello,
> 
> Are you using any kind if software such as screen recorders, game overlays (for example nvidia overlay) or any other software thay may capture/render/cover the whole screen?

Hi Marti 
thank you for your swift reply, I think I know which program it may be https://www.nelsonpires.com/software/dimmer
Dimmer controls the brightness of your screens and Flux adds a colour tint in the evening. https://justgetflux.com/
Would there be a possibility to work around these apps at all? Even when these are running; eleven clock does run sometimes.
Thank you once again for your time
Cy

**Comment by marticliment** [comment]
Try to set ElevenClock to not hide when an app is in fullscreen and see if this works

**Comment by Cypherthegreat** [comment]
This does work however, If I am watching a video or playing a game the clock will be stuck on top of the screen.

**Comment by marticliment** [comment]
I am afraid there is no fix for this issue, since there is no way for ElevenClock to distinct between your fullscreen chrome window and the screen dimmer.

**Comment by Cypherthegreat** [comment]
Thank you, I think that is the best work around. I really appreciate your help and hard work.
Have a great evening
