### ISSUE TITLE
[ENHANCEMENT] (Support for applying bold font to clock)

### ISSUE THREAD

**Issue by abcd123666** [marticliment/ElevenClock#1327]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Currently, I only have the option to choose the regular style while bold for certain fonts would be the best for improved readability.

### Describe how this improvement could help users.

Just for a comfier clock with some fonts.

**Comment by marticliment** [comment]
Yo should be able to do so, which ElevenClock version are you running?

![image](https://github.com/marticliment/ElevenClock/assets/53119851/e5ba01c7-14a4-4b5a-8b9f-05b091925330)

**Comment by abcd123666** [comment]
You are right, but the specific custom font I'm using, which is Anonymous Pro Regular, doesn't allow to pick the bold style, I guess this is because I didn't install the bold font separately due to it changing the shape of the font entirely to Consolas-like instead. I was able to set up the bold from regular in Windows Explorer, VSC, Firefox, MySQL Workbench, DBeaver, mIRC.. some doing it natively when the font is installed and picked, while with others having to resort to .css or .json config files, but there's no way I can put this specific font in bold with this software. I would very much appreciate if you can do this, testing the font if you like by installing the regular-only .ttf.

Obviously I'll keep using your program as it is very useful (the default clock is minuscule, specially with high res panels).

I appreciate all your efforts and sincerely wish you the best in your projects. Regards.

**Comment by marticliment** [comment]
I will investigate this, but I can't guarantee anything

**Comment by marticliment** [comment]
I am afraid there appears to exist a bug with Qt and some fonts. Therefore, I can't fix this from ElevenClock
