### ISSUE TITLE
[BUG] (When I click Ethernet/Volume icon ElevenClock disappears. Windows 11 24H2 26100.268)

### ISSUE THREAD

**Issue by D3ZOXY** [marticliment/ElevenClock#1342]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

When I click Ethernet/Volume icon ElevenClock disappears.

### Steps to reproduce the issue

1. Install ElevenClock 4.3.3 on Windows 11 24H2 26100.268.
2. Click Ethernet/Volume icon.

### ElevenClock Log

[Logs_ElevenClock_4.3.3.txt](https://github.com/marticliment/ElevenClock/files/15326055/Logs_ElevenClock_4.3.3.txt)

### Screenshots and videos

https://github.com/marticliment/ElevenClock/assets/47178587/1e5366b4-afe6-464c-87dd-18142a79a78c

**Comment by marticliment** [comment]
When the taskbar has focus the clock hides, since anything can draw over a focused window on Windows. Once the taskbar loses focus the clock will show again

**Comment by D3ZOXY** [comment]
Can you make when taskbar has focus the clock will be always unhidden and on top of all windows?

**Comment by marticliment** [comment]
Yes, but since the taskbar has the focus it wins
