### ISSUE TITLE
Transparenter Uhren Hintergrund

### ISSUE THREAD

**Issue by EynMarcvonSenn** [marticliment/ElevenClock#1351]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).

### Describe the new feature

Einstellung um Hintergrund Transparent zu stellen, also man sieht nur noch die Uhren anzeige.

### Describe how this new feature could help users

Schöner und ohne Schwarzer Hintergrund

**Comment by marticliment** [comment]
Hello, you can make the clock transparent by changing the alpha channel in the Background Color.

Btw, please post in english. Thanks!
