### ISSUE TITLE
[ENHANCEMENT] Hide Clock on second monitor when working with multi-monitors

### ISSUE THREAD

**Issue by kiloforce** [marticliment/ElevenClock#1361]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

I am not sure if Windows 11 changed the default behavior at some point, which makes this request the opposite of #1320 .  The clock is shows up by default on both of my monitors, and I want the opposite.

I like to have maximum room on my taskbar, as I have a ton of development applications open, so I turn off and hide all the extra garbage, like hiding the Search Bar, hiding the Widgets, hiding the Copilot, and collapsing all of the system bar icons.  I have even had my clock hidden to maximize the taskbar room (especially since it shows up twice, once on each monitor).  But I often have found myself wanting at least one copy of the clock back.

I started searching for a way to hide one copy of the clock, and I then found ElevenClock, but for the opposite reason.  I then learned the default behavior in Windows 11 was that the clock would only show up on the primary monitor?  How do I get that behavior?  Or how can I have ElevenClock do its thing to override Windows 11 behavior?

### Describe how this improvement could help users

Expanded room on the taskbar.

"Guess what! I've got a fever, and the only prescription is more taskbar!"  /s

**Comment by marticliment** [comment]
Right-click clock -> Clock tools -> hide this clock

**Comment by kiloforce** [comment]
@marticliment thank you for responding.  It looks like the feature is supposed to be there, but the "effect" appears to be missing?  When I click "_hide this clock_" I get a quick flash, like it tried to hide the clock, but the clock remains.  When I try to right click on the clock again, the context menu that included the "hide this clock" is no longer there.  This hide functionality should work on Windows 11 (23H2 build 22631.3958)?

**Comment by marticliment** [comment]
Yoy should be using this option: 
![image](https://github.com/user-attachments/assets/5867b0d4-1e00-4534-ae5a-b99439018533)
