### ISSUE TITLE
[ENHANCEMENT] (Enter your description here)

### ISSUE THREAD

**Issue by tomiweb** [marticliment/ElevenClock#1371]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

existe una opcion para mostrar a la derecha un reloj y a la izquierda uno diferente. para tener 2 zonas horarias. gracias

### Describe how this improvement could help users

existe una opcion para mostrar a la derecha un reloj y a la izquierda uno diferente. para tener 2 zonas horarias. gracias

**Comment by marticliment** [comment]
Si vas a Configuración de ElevenClock -> Configuración del reloj, verás una opción para "Mostrar un segondo reloj en el otro lado de la barra de tareas".

Una vez ahí, haz click derecho en el nuevo reloj -> Herramientas del reloj -> Configuración para este reloj -> Configuración de la fecha y hora -> Establece un formato de fecha y hora personalizado -> y especifica un formato con un offset de tiempo

**Comment by tomiweb** [comment]
Gracias!!
