### ISSUE TITLE
[BUG] Notification Area / Taskbar Flickering

### ISSUE THREAD

**Issue by tjsuominen** [marticliment/ElevenClock#1377]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose)).

### Describe your issue

Upon moving mouse cursor on Windows Taskbar (on/off) OR on Taskbar Icons (on/off) or Taskbar Minimized App Icons, the ElevenClock area / Windows Notification Bell flickers strangely (and Notification Bell shows 'New Items / No New Items'). See linked Video for clarification. This is a bit disturbing.

### Steps to reproduce the issue

See linked Video.

https://github.com/user-attachments/assets/6d00acdf-e1b5-4330-b569-504d857cd83f

### ElevenClock Log

```text
11Clock Log

[11ClockLog.txt](https://github.com/user-attachments/files/17586566/11ClockLog.txt)
```

### Relevant information

11Clock Log

[11ClockLog.txt](https://github.com/user-attachments/files/17586566/11ClockLog.txt)

### Screenshots and videos

See linked Video.

https://github.com/user-attachments/assets/6d00acdf-e1b5-4330-b569-504d857cd83f

**Comment by marticliment** [comment]
Please see the known issues: https://github.com/marticliment/ElevenClock/wiki#known-issues
