### ISSUE TITLE
[FEATURE REQUEST] Support movable taskbars by drawing background "blocking" rectangle where Windows clock was rendered

### ISSUE THREAD

**Issue by manicottiK** [marticliment/ElevenClock#1393]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).

### Describe the new feature

When the taskbar is moved to the top or sides via tools like Start11, ExplorerPatcher, etc., ElevenClock still tests for the taskbar background color at the bottom right of the screen AND it still draws a background color rectangle to block the old clock. Users should be able to indicate where the system-drawn clock is located so that the background color test and the blocking rectangle drawing is done at the correct location (bottom-right, bottom-left, top-right).
![Screenshot 2024-12-16 085104](https://github.com/user-attachments/assets/e1273b82-3b85-427e-8c51-7b9d25d71371)

### Describe how this new feature could help users

Would stop ElevenClock from blocking active on-screen content and controls (e.g., blocking lower right scrollbar controls when taskbar is at top or left).

**Comment by marticliment** [comment]
You may want to disable native clock covering:
 - ElevenClock settings -> Experimental features -> Disable covering the Default windows clock

**Comment by manicottiK** [comment]
That works for me. Thank you very much. (I did look for some sort of setting to do this, but obviously not well enough. Sorry to bother you with a request that you had already accommodated.)
